---
settings:
  name: Active IQ Unified Manager 9.16
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.16'
    url: "/active-iq-unified-manager"
  - version-number: '9.14'
    url: "/active-iq-unified-manager-914"
  - version-number: '9.13'
    url: "/active-iq-unified-manager-913"
  - version-number: '9.12'
    url: "/active-iq-unified-manager-912"
  - version-number: '9.11'
    url: "/active-iq-unified-manager-911"
  - version-number: '9.10'
    url: "/active-iq-unified-manager-910"
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents relatifs à Active IQ Unified Manager 9.16
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/reference_release_notes.html"
  - title: Commencez
    entries:
    - title: Installation de démarrage rapide pour VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installation de démarrage rapide pour Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installation de démarrage rapide pour Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Mentions légales
    url: "/legal-notices.html"
