---
permalink: api-automation/concept_rest_api_access_and_authentication_in_um_apis.html 
sidebar: sidebar 
keywords: rest api, access, authentication, active iq, unified, manager 
summary: 'L"API REST de Active IQ Unified Manager est accessible depuis n"importe quel navigateur web ou plateforme de programmation pouvant émettre des requêtes HTTP. Unified Manager prend en charge le mécanisme d"authentification HTTP de base. Avant d"appeler l"API REST Unified Manager, vous devez authentifier un utilisateur.' 
---
= Accès à l'API REST et authentification dans Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'API REST Active IQ Unified Manager est accessible depuis n'importe quel client REST ou plateforme de programmation pouvant émettre des requêtes HTTP avec un mécanisme d'authentification HTTP de base.

Exemple de demande et de réponse :

* *Demande*
+
[listing]
----
GET
https://<IP address/hostname>:<port_number>/api/v2/datacenter/cluster/clusters
----
* *Réponse*
+
[listing]
----
{
  "records": [
    {
      "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "name": "fas8040-206-21",
      "uuid": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "contact": null,
      "location": null,
      "version": {
        "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
        "generation": 9,
        "major": 5,
        "minor": 0
      },
      "isSanOptimized": false,
      "management_ip": "10.226.207.25",
      "nodes": [
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "uuid": "12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "name": "fas8040-206-21-01",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 13924095,
          "serial_number": "701424000157"
        },
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "uuid": "1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "name": "fas8040-206-21-02",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 14012386,
          "serial_number": "701424000564"
        }
      ],
      "_links": {
        "self": {
          "href": "/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb"
        }
      }
    },
----
+
** `_IP address/hostname_` Est l'adresse IP ou le nom de domaine complet (FQDN) du serveur d'API.
** Orifice 443
+
Le port HTTPS par défaut est défini sur 443. Vous pouvez personnaliser le port HTTPS si nécessaire.



+
Pour émettre des requêtes HTTP à partir d'un navigateur Web, vous devez utiliser des plug-ins de navigateur d'API REST. Vous pouvez également accéder à l'API REST à l'aide de plateformes de script telles que curl et Perl.





== Authentification

Unified Manager prend en charge le schéma d'authentification HTTP de base pour les API. Pour sécuriser les flux d'informations (demande et réponse), les API REST sont accessibles uniquement via HTTPS. Le serveur d'API fournit un certificat SSL auto-signé à tous les clients pour la vérification du serveur. Ce certificat peut être remplacé par un certificat personnalisé (ou un certificat CA).

Vous devez configurer l'accès utilisateur au serveur d'API pour appeler les API REST. Les utilisateurs peuvent être des utilisateurs locaux (profils utilisateur stockés dans la base de données locale) ou des utilisateurs LDAP (si vous avez configuré le serveur d'API pour s'authentifier via LDAP). Vous pouvez gérer l'accès des utilisateurs en vous connectant à l'interface utilisateur de la console d'administration de Unified Manager.
