---
permalink: reporting/task_download_reports.html 
sidebar: sidebar 
keywords: download, reports 
summary: 'Vous pouvez télécharger des rapports et enregistrer les données sur un lecteur local ou réseau sous la forme d"un fichier CSV (valeurs séparées par des virgules), d"un fichier Microsoft Excel (.XLSX) ou d"un fichier PDF. Vous pouvez ouvrir des fichiers CSV et XLSX avec des applications de tableur, telles que Microsoft Excel, et des fichiers PDF avec des lecteurs comme Adobe Acrobat.' 
---
= Téléchargement de rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez télécharger des rapports et enregistrer les données sur un lecteur local ou réseau sous la forme d'un fichier CSV (valeurs séparées par des virgules), d'un fichier Microsoft Excel (.XLSX) ou d'un fichier PDF. Vous pouvez ouvrir des fichiers CSV et XLSX avec des applications de tableur, telles que Microsoft Excel, et des fichiers PDF avec des lecteurs comme Adobe Acrobat.

.Étapes
. Cliquez sur le bouton *Rapports* pour télécharger le rapport comme suit :
+
[cols="2*"]
|===
| Choisissez | Pour... 


 a| 
Télécharger CSV
 a| 
Enregistrez le rapport sous la forme d'un fichier CSV (valeurs séparées par des virgules).



 a| 
Télécharger le PDF
 a| 
Enregistrez le rapport en tant que fichier .PDF.



 a| 
Téléchargez Excel
 a| 
Enregistrez le rapport sous forme de fichier Microsoft Excel (XLSX).

|===

