---
permalink: performance-checker/concept_um_interfaces_used_to_manage_storage_system_performance.html 
sidebar: sidebar 
keywords: unified manager, interfaces, used, manage, storage, system, performance, web ui, maintenance, console 
summary: 'Active IQ Unified Manager fournit deux interfaces utilisateur pour le contrôle et la résolution des problèmes de performances du stockage des données : l"interface utilisateur Web et la console de maintenance.' 
---
= Interfaces Unified Manager utilisées pour gérer les performances du système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ces sections contiennent des informations sur les deux interfaces utilisateur fournies par Active IQ Unified Manager pour résoudre les problèmes de capacité, de disponibilité et de protection du stockage des données. Les deux interfaces utilisateur sont l'interface utilisateur Web de Unified Manager et la console de maintenance.

Si vous souhaitez utiliser les fonctions de protection dans Unified Manager, vous devez également installer et configurer OnCommand Workflow Automation (WFA).



== Interface Web Unified Manager

L'interface utilisateur Web Unified Manager permet à un administrateur de surveiller et de résoudre les problèmes liés à la capacité de stockage, à la disponibilité et à la protection des données en cluster.

Ces sections décrivent les flux de travail courants qu'un administrateur peut suivre pour résoudre les problèmes de capacité de stockage, de disponibilité des données ou de protection affichés dans l'interface utilisateur Web Unified Manager.



== Console de maintenance

La console de maintenance Unified Manager permet à un administrateur de surveiller, diagnostiquer et résoudre les problèmes liés au système d'exploitation, à la mise à niveau de la version, aux problèmes d'accès utilisateur et aux problèmes de réseau liés au serveur Unified Manager lui-même. Si l'interface utilisateur Web de Unified Manager n'est pas disponible, la console de maintenance est la seule forme d'accès à Unified Manager.

Vous pouvez utiliser ces informations pour accéder à la console de maintenance et l'utiliser pour résoudre les problèmes liés au fonctionnement du serveur Unified Manager.
