---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: 'Les groupes de règles de QoS adaptative ajustent automatiquement un plafond ou un sol de débit en fonction de la taille du volume. Ainsi, ils maintiennent le rapport IOPS/To en fonction de la taille du volume. Depuis la version ONTAP 9.5, vous pouvez spécifier la taille de bloc dans la règle de QoS afin d"appliquer efficacement un seuil Mo/s en même temps.' 
---
= Comprendre les événements des politiques QoS adaptatives qui ont une taille de bloc définie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les groupes de règles de QoS adaptative ajustent automatiquement un plafond ou un sol de débit en fonction de la taille du volume. Ainsi, ils maintiennent le rapport IOPS/To en fonction de la taille du volume. Depuis la version ONTAP 9.5, vous pouvez spécifier la taille de bloc dans la règle de QoS afin d'appliquer efficacement un seuil Mo/s en même temps.

L'assignation d'un seuil IOPS dans une règle de QoS adaptative impose une limite uniquement au nombre d'opérations qui se produisent dans chaque workload. En fonction de la taille de bloc définie sur le client qui génère les workloads, certains IOPS incluent beaucoup plus de données et, par conséquent, alourdit considérablement la charge de travail sur les nœuds qui traitent les opérations.

La valeur MB/s d'une charge de travail est générée à l'aide de la formule suivante :

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
Si une charge de travail moyenne est de 3,000 000 IOPS et que la taille de bloc sur le client est définie sur 32 Ko, la valeur réelle en Mo/s pour cette charge de travail est de 96. Si cette même charge de travail moyenne est de 3,000 000 IOPS et que la taille de bloc du client est définie sur 48 Ko, la capacité effective en Mo/s de cette charge de travail est de 144. Vous pouvez constater que le nœud traite 50 % de données en plus lorsque la taille de bloc est supérieure.

Examinons la règle de QoS adaptative suivante avec une taille de bloc définie et le mode de déclenchement des événements en fonction de la taille de bloc définie sur le client.

Créez une règle et définissez le débit maximal sur 2,500 IOPS/To avec une taille de bloc de 32 Ko. Cette configuration définit ainsi le seuil en Mo/s à 80 Mo/s ((2500 IOPS * 32 Ko) / 1000) pour un volume dont la capacité utilisée est de 1 To. Notez que Unified Manager génère un événement Avertissement lorsque la valeur de débit est inférieure de 10 % au seuil défini. Les événements sont générés dans les situations suivantes :

|===
| Capacité utilisée 2+| L'événement est généré lorsque le débit dépasse ce nombre de ... 


|  | D'IOPS | Mo/s 


 a| 
1 To
 a| 
2,250 000 IOPS
 a| 
72 Mo/s



 a| 
2 To
 a| 
4,500 000 IOPS
 a| 
144 Mo/s



 a| 
5 TO
 a| 
11,250 000 IOPS
 a| 
360 Mo/s

|===
Si le volume utilise 2 To d'espace disponible et que les IOPS sont de 4,000 et que la taille de bloc de QoS est définie sur 32 Ko pour le client, le débit en Mo/s est de 128 Mo/s ((4,000 IOPS * 32 Ko) / 1000). Aucun événement n'est généré dans ce scénario car 4,000 IOPS et 128 Mo/s sont tous les deux inférieurs au seuil d'un volume utilisant 2 To d'espace.

Si le volume utilise 2 To d'espace disponible et que le nombre d'IOPS est de 4,000 et que la taille de bloc de QoS est définie sur 64 Ko sur le client, le débit de Mo/s est de 256 Mo/s ((4,000 IOPS * 64 Ko) / 1000). Dans ce cas, les 4,000 IOPS ne génèrent pas d'événement, mais la valeur MB/s de 256 MB/s est au-dessus du seuil de 144 MB/s et un évènement est généré.

Par conséquent, lorsqu'un événement est déclenché en fonction d'une violation MB/s pour une stratégie QoS adaptative qui inclut la taille du bloc, un graphique MB/s s'affiche dans la section diagnostic système de la page Détails de l'événement. Si l'événement est déclenché en fonction d'une violation des IOPS de la règle de QoS adaptative, un graphique Op E/S par sec s'affiche dans la section diagnostic système. Si une violation se produit à la fois pour les IOPS et les Mo/s, vous recevrez deux événements.

Pour plus d'informations sur le réglage des paramètres QoS, voir https://docs.netapp.com/us-en/ontap/performance-admin/index.html["Présentation de la gestion des performances"].
