---
permalink: performance-checker/concept_understand_performance_events_and_alerts.html 
sidebar: sidebar 
keywords: understand, performance, events, alerts 
summary: 'Les événements de performance sont des notifications qu"Unified Manager génère automatiquement lorsqu"une condition prédéfinie se produit ou lorsqu"une valeur de compteur de performances franchit un seuil. Les événements vous aident à identifier les problèmes de performance dans les clusters surveillés.' 
---
= Présentation des événements de performances et des alertes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les événements de performance sont des incidents liés aux performances des charges de travail sur un cluster. Ils vous aident à identifier les workloads avec des temps de réponse lents. Avec les événements de santé qui se sont produits en même temps, vous pouvez déterminer les problèmes qui pourraient avoir causé, ou contribué à, les délais de réponse lents.

Lorsque Unified Manager détecte plusieurs occurrences de la même condition d'événement pour le même composant de cluster, il traite toutes les occurrences comme un événement unique et non comme des événements distincts.

Vous pouvez configurer des alertes pour envoyer automatiquement une notification par e-mail lorsque des événements de performance de certains types de gravité se produisent.
