---
permalink: performance-checker/task_view_volume_and_lun_latency_charts_to_verify_performance_guarantee.html 
sidebar: sidebar 
keywords: view, volume, lun, latency, charts, verify, performance, guarantee 
summary: 'Vous pouvez afficher les volumes et les LUN que vous avez souscrits au programme « garantie de performances » pour vérifier que la latence n"a pas dépassé le niveau garanti.' 
---
= Affichage des graphiques de latence des volumes et des LUN pour vérifier la performance garantie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les volumes et les LUN que vous avez souscrits au programme « garantie de performances » pour vérifier que la latence n'a pas dépassé le niveau garanti.

La garantie de latence est une valeur inférieure à la milliseconde par opération, qui ne doit pas être dépassée. Elle est basée sur une moyenne horaire et non sur la période de collecte de performances de cinq minutes par défaut.

.Étapes
. Dans la vue *Performance : tous les volumes* ou *Performance : toutes les LUN*, sélectionnez le volume ou la LUN qui vous intéresse.
. Dans la page *Performance Explorer* de votre volume ou LUN sélectionné, choisissez *moyenne horaire* dans le sélecteur *Afficher les statistiques dans*.
+
La ligne horizontale du graphique latence affiche une ligne plus lisse lorsque les collections de cinq minutes sont remplacées par la moyenne horaire.

. Si d'autres volumes sont présents sur le même agrégat et sont garantis par performances, vous pouvez ajouter ces volumes pour afficher leur valeur de latence sur le même graphique.

