---
permalink: performance-checker/task_edit_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: edit, user-defined, performance, threshold, policies 
summary: 'Vous pouvez modifier les paramètres de seuil des règles de seuils de performances existantes. Cela peut être utile si vous constatez que vous recevez trop ou trop peu d"alertes pour certaines conditions de seuil.' 
---
= Modifier les politiques de seuil de performance définies par l'utilisateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres de seuil des règles de seuils de performances existantes. Cela peut être utile si vous constatez que vous recevez trop ou trop peu d'alertes pour certaines conditions de seuil.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications.

Vous ne pouvez pas modifier le nom de la règle ou le type d'objet de stockage actuellement contrôlé pour les règles de seuils existantes.

.Étapes
. Dans le volet de navigation de gauche, sélectionnez *seuils d'événements* > *performances*.
+
La page seuils de performance s'affiche.

. Sélectionnez la stratégie de seuil à modifier et cliquez sur *Modifier*.
+
La page Modifier la stratégie de seuil de performances s'affiche.

. Apportez vos modifications à la stratégie de seuil et cliquez sur *Enregistrer*.
+
Vous êtes renvoyé à la page seuils de performances.



Une fois qu'elles ont été enregistrées, les modifications sont immédiatement mises à jour sur tous les objets de stockage qui utilisent la règle.

En fonction du type de modifications apportées à la règle, vous pouvez consulter les paramètres d'alerte configurés pour les objets qui utilisent la règle dans la page Configuration des alertes.
