---
permalink: storage-mgmt/task_create_an_email_notification_format.html 
sidebar: sidebar 
keywords: create, email, notification, format, user, group, quotas 
summary: 'Vous pouvez créer un format de notification pour les e-mails envoyés à un utilisateur ou à un groupe d"utilisateurs en cas de problème lié à un quota (limite souple dépassée ou limite stricte atteinte).' 
---
= Création d'un format de notification par e-mail pour les quotas d'utilisateurs et de groupes d'utilisateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un format de notification pour les e-mails envoyés à un utilisateur ou à un groupe d'utilisateurs en cas de problème lié à un quota (limite souple dépassée ou limite stricte atteinte).

*Ce dont vous aurez besoin*

Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *général* > *quota Email format*.
. Saisissez ou modifiez les détails dans les champs *de*, *sujet* et *Détails de l'adresse électronique*.
. Cliquez sur *Aperçu* pour afficher un aperçu de la notification par e-mail.
. Cliquez sur *Fermer* pour fermer la fenêtre d'aperçu.
. Modifiez le contenu de la notification par e-mail, si nécessaire.
. Cliquez sur *Enregistrer*.

