---
permalink: storage-mgmt/task_view_user_and_user_group_quotas.html 
sidebar: sidebar 
keywords: view, user, user, group, quotas 
summary: 'La page d"informations Storage VM / Health affiche des informations sur les quotas d"utilisateur et de groupe d"utilisateurs configurés sur la SVM. Vous pouvez afficher le nom de l"utilisateur ou du groupe d"utilisateurs, les limites définies sur les disques et les fichiers, l"espace disque et fichier utilisés et l"adresse e-mail de notification.' 
---
= Affichage des quotas d'utilisateurs et de groupes d'utilisateurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page d'informations Storage VM / Health affiche des informations sur les quotas d'utilisateur et de groupe d'utilisateurs configurés sur la SVM. Vous pouvez afficher le nom de l'utilisateur ou du groupe d'utilisateurs, les limites définies sur les disques et les fichiers, l'espace disque et fichier utilisés et l'adresse e-mail de notification.

.Avant de commencer
Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage* > *Storage VM*.
. Dans la vue *Santé : toutes les machines virtuelles de stockage*, sélectionnez une machine virtuelle de stockage, puis cliquez sur l'onglet *quotas d'utilisateur et de groupe*.


*Informations connexes*

link:../config/task_add_users.html["Ajout d'utilisateurs"]
