---
permalink: storage-mgmt/task_view_list_of_monitored_clusters.html 
sidebar: sidebar 
keywords: view, list, monitored, clusters 
summary: 'Vous pouvez utiliser la page Cluster Setup pour afficher l"inventaire de vos clusters. Vous pouvez afficher des détails sur les clusters, tels que leur nom ou leur adresse IP et l"état de la communication.' 
---
= Afficher la liste des clusters surveillés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la page Cluster Setup pour afficher l'inventaire de vos clusters. Vous pouvez afficher des détails sur les clusters, tels que leur nom ou leur adresse IP et l'état de la communication.

.Avant de commencer
Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.

.Étape
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Cluster Setup*.
+
Tous les clusters de votre environnement de stockage géré par Unified Manager sont affichés.la liste des clusters est triée par colonne du niveau de gravité de l'état de collecte. Vous pouvez cliquer sur un en-tête de colonne pour trier les clusters par différentes colonnes.


