---
permalink: storage-mgmt/task_create_rules_to_generate_email_addresses.html 
sidebar: sidebar 
keywords: create, rules, generate, email, addresses 
summary: 'Vous pouvez créer des règles pour spécifier l"adresse e-mail en fonction du quota d"utilisateur associé aux clusters, aux SVM (Storage Virtual machine), aux volumes, aux qtrees, aux utilisateurs ou aux groupes d"utilisateurs. Une notification est envoyée à l"adresse e-mail spécifiée lorsqu"une violation de quota est constatée.' 
---
= Création de règles pour générer des adresses e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des règles pour spécifier l'adresse e-mail en fonction du quota d'utilisateur associé aux clusters, aux SVM (Storage Virtual machine), aux volumes, aux qtrees, aux utilisateurs ou aux groupes d'utilisateurs. Une notification est envoyée à l'adresse e-mail spécifiée lorsqu'une violation de quota est constatée.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir passé en revue les directives de la page règles de génération de l'adresse e-mail de quota d'utilisateur et de groupe.


Vous devez définir les règles pour les adresses e-mail de quota et les saisir dans l'ordre dans lequel vous souhaitez les exécuter. Par exemple, si vous souhaitez utiliser l'adresse e-mail abc@xyz.com pour recevoir des notifications sur les violations de quota pour abc et utiliser l'adresse e-mail dl-$GROUP@$DOMAIN pour tous les autres groupes, les règles doivent être répertoriées dans l'ordre suivant :

* Si ( $USER == 'abc' ) alors abc@xyz.com
* Si ( $GROUP == * ) alors dl-$GROUP@$DOMAIN


Si aucun des critères pour les règles que vous avez spécifiées n'est satisfait, la règle par défaut est utilisée :

SI ($USER_OR_GROUP == * ), ALORS $USER_OR_GROUP@$DOMAIN

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *général* > *quota Email Rules*.
. Saisissez la règle en fonction de vos critères.
. Cliquez sur *Validate* pour valider la syntaxe de la règle.
+
Un message d'erreur s'affiche si la syntaxe de la règle est incorrecte. Vous devez corriger la syntaxe et cliquer à nouveau sur *Validate*.

. Cliquez sur *Enregistrer*.
. Vérifiez que l'adresse e-mail que vous avez créée s'affiche dans l'onglet *quotas d'utilisateurs et de groupes* de la page Détails Storage *VM / Health*.

