---
permalink: health-checker/concept_manage_cluster_security_objectives.html 
sidebar: sidebar 
keywords: cluster, security, manage, objectives 
summary: Unified Manager fournit un tableau de bord identifiant la sécurité des clusters ONTAP, des machines virtuelles de stockage et des volumes, selon les recommandations définies dans le guide NetApp sur le renforcement de la sécurité des environnements ONTAP 9. 
---
= Gestion des objectifs de sécurité des clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager fournit un tableau de bord identifiant la sécurité de vos clusters ONTAP, de vos serveurs de stockage virtuels (SVM) et de vos volumes à partir des recommandations définies dans le _guide NetApp de renforcement de la sécurité des environnements ONTAP 9_.

L'objectif du tableau de bord de sécurité est de fournir des informations sur les zones dans lesquelles les clusters ONTAP ne sont pas en adéquation avec les instructions recommandées par NetApp afin de résoudre ces problèmes potentiels. Dans la plupart des cas, vous pouvez résoudre les problèmes à l'aide de ONTAP System Manager ou de l'interface de ligne de commandes de ONTAP. Il se peut que votre organisation ne suive pas toutes les recommandations. Dans certains cas, vous n'aurez donc pas besoin d'apporter de modifications.

Voir la http://www.netapp.com/us/media/tr-4569.pdf["Guide NetApp sur le renforcement de la sécurité des environnements ONTAP 9"] (Tr-4569) pour des recommandations et des résolutions détaillées.

En plus de signaler l'état de sécurité, Unified Manager génère également des événements de sécurité pour tout cluster ou SVM présentant des violations de sécurité. Vous pouvez suivre ces problèmes dans la page d'inventaire de la gestion des événements et configurer les alertes pour ces événements de sorte que votre administrateur de stockage soit averti en cas de nouveaux événements de sécurité.

Pour plus d'informations, voir link:../health-checker/concept_what_security_criteria_is_being_evaluated.html["Quels sont les critères de sécurité évalués"].
