---
permalink: health-checker/concept_configure_backup_for_linux.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies, linux, operate, system, configure, backup 
summary: 'Si votre Active IQ Unified Manager est installé sur un ordinateur Linux, vous pouvez décider de configurer votre sauvegarde et restauration à l"aide des snapshots NetApp.' 
---
= Configurer la sauvegarde sous Linux dans Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre Active IQ Unified Manager est installé sur un ordinateur Linux, vous pouvez décider de configurer votre sauvegarde et restauration à l'aide des snapshots NetApp.

Les copies Snapshot prennent très peu de temps, en général quelques minutes seulement, et la base de données Unified Manager est verrouillée pendant un très court laps de temps. Vous n'avez donc que peu d'interruptions dans votre installation. L'image consomme un espace de stockage minimal et entraîne une surcharge minime des performances, car elle enregistre uniquement les modifications apportées aux fichiers depuis la dernière copie Snapshot. Comme la copie Snapshot est créée sur un cluster ONTAP, vous pouvez utiliser d'autres fonctionnalités NetApp, telles que SnapMirror, pour créer une protection secondaire, si nécessaire.

Avant de lancer une opération de sauvegarde, Unified Manager effectue une vérification d'intégrité afin de vérifier que le système de destination est disponible.

[NOTE]
====
* Vous ne pouvez restaurer une copie Snapshot que sur la même version de Active IQ Unified Manager.
+
Par exemple, si vous avez créé une sauvegarde sur Unified Manager 9.18, la sauvegarde ne peut être restaurée que sur les systèmes Unified Manager 9.18.

* Si une modification est apportée à la configuration de Snapshot, celle-ci peut ne pas être valide.


====


[[configure-snapshot-copy-location-in-active-iq-unified-manager]]
== Configurer l'emplacement de la copie Snapshot dans Active IQ Unified Manager

Vous pouvez configurer le volume sur lequel les copies Snapshot seront stockées sur l'un de vos clusters ONTAP à l'aide de ONTAP System Manager ou de l'interface de ligne de commandes ONTAP.

.Avant de commencer
Le cluster, la VM de stockage et le volume doivent satisfaire aux exigences suivantes :

* Configuration requise pour le cluster :
+
** ONTAP 9.3 ou version ultérieure doit être installé
** Elle doit se trouver géographiquement proche du serveur Unified Manager
** Il peut être surveillé par Unified Manager, mais ce n'est pas nécessaire


* Configuration requise pour les machines virtuelles de stockage :
+
** Le commutateur de nom et le mappage de nom doivent être définis pour utiliser « fichiers ».
** Les utilisateurs locaux créés pour correspondre aux utilisateurs côté client
** Assurez-vous que tous les accès en lecture/écriture sont sélectionnés
** Assurez-vous que Superuser Access est défini sur « n'importe quel » dans la politique d'exportation
** NFS pour NetApp Snapshot pour Linux
** NFSv4 doit être activé sur le serveur NFS et le domaine ID NFSv4 spécifié sur le client et le VM de stockage
** Le volume doit avoir au moins deux fois la taille du répertoire Unified Manager/opt/netapp/Data
+
Utilisez la commande du -sh /opt/netapp/data/ pour vérifier la taille actuelle.



* Volume requis :
+
** Le volume doit avoir au moins deux fois la taille du répertoire Unified Manager /opt/netapp/data
** Le style de sécurité doit être défini sur UNIX
** La stratégie de snapshot local doit être désactivée
** La taille automatique du volume doit être activée
** Le niveau de services de performance doit être défini à une règle avec des IOPS élevées et une faible latence, telles que « extrême »




Pour obtenir des instructions détaillées sur la création du volume NFS, reportez-vous à la section https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["Comment configurer NFSv4 dans ONTAP 9"] et le http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["Guide de configuration rapide ONTAP 9 NFS"].



[[specify-the-destination-location-for-snapshot-copies-in-active-iq-unified-manager]]
== Spécifiez l'emplacement de destination des copies Snapshot dans Active IQ Unified Manager

Vous devez configurer l'emplacement de destination des copies Snapshot Active IQ Unified Manager sur un volume que vous avez déjà configuré dans l'un de vos clusters ONTAP. Vous devez utiliser la console de maintenance pour définir l'emplacement.

* Vous devez disposer des informations d'identification utilisateur root pour l'hôte Linux sur lequel Active IQ Unified Manager est installé.
* Vous devez disposer d'un ID utilisateur et d'un mot de passe autorisés pour vous connecter à la console de maintenance du serveur Unified Manager.
* Vous devez disposer de l'adresse IP de gestion de cluster, du nom de la machine virtuelle de stockage, du nom du volume, ainsi que du nom d'utilisateur et du mot de passe du système de stockage.
* Vous devez avoir monté le volume sur l'hôte Active IQ Unified Manager, et vous devez disposer du chemin de montage.


.Étapes
. Utilisez Secure Shell pour vous connecter à l'adresse IP ou au FQDN du système Active IQ Unified Manager.
. Connectez-vous au système avec le nom et le mot de passe de l'utilisateur de maintenance (umadmin).
. Saisissez la commande `maintenance_console` Puis appuyez sur entrée.
. Dans la console de maintenance *Menu principal*, saisissez le numéro de l'option *Sauvegarder Restaurer*.
. Entrez le numéro *configurer la sauvegarde NetApp Snapshot*.
. Indiquez le nombre de configurations NFS.
. Vérifiez les informations que vous devez fournir, puis saisissez le numéro de *entrer les détails de la configuration de sauvegarde*.
. Pour identifier le volume sur lequel la copie Snapshot sera écrite, entrez l'adresse IP de l'interface de gestion du cluster, le nom du VM de stockage, le nom du volume, le nom de la LUN, le nom d'utilisateur et le mot de passe du système de stockage, ainsi que le chemin de montage.
. Vérifiez ces informations et entrez `y`.
+
Le système effectue les tâches suivantes :

+
** Établit la connexion avec le cluster
** Arrête tous les services
** Crée un nouveau répertoire dans le volume et copie les fichiers de configuration de la base de données Active IQ Unified Manager
** Supprime les fichiers de Active IQ Unified Manager et crée un lien symbolique vers le nouveau répertoire de base de données
** Redémarre tous les services


. Quittez la console de maintenance et lancez l'interface Active IQ Unified Manager pour créer une planification de la copie Snapshot si vous ne l'avez pas encore fait.

