---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: 'Active IQ Unified Manager prend en charge les sauvegardes et les restaurations à l"aide de snapshots NetApp sur le système d"exploitation Windows à l"aide du protocole iSCSI.' 
---
= Configurer la sauvegarde sous Windows dans Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager prend en charge les sauvegardes et les restaurations à l'aide de snapshots NetApp sur le système d'exploitation Windows à l'aide du protocole iSCSI.

Une sauvegarde basée sur des snapshots peut être effectuée pendant l'exécution de tous les services Unified Manager. Un état cohérent de la base de données est capturé dans le cadre de la copie Snapshot, tandis que la sauvegarde place un verrouillage de lecture global sur l'ensemble de la base de données, ce qui empêche toute écriture simultanée. Pour que votre système Unified Manager soit installé sur le système d'exploitation Windows pour effectuer des sauvegardes et des restaurations à l'aide des snapshots NetApp, vous devez d'abord configurer la sauvegarde Unified Manager sur des copies Snapshot à l'aide de la console de maintenance.

Avant de configurer Unified Manager pour la création de copies Snapshot, vous devez effectuer les tâches de configuration suivantes.

* Configurez le cluster ONTAP
* Configurer la machine hôte Windows




[[configure-a-backup-location-for-active-iq-unified-manager-on-windows]]
== Configurez un emplacement de sauvegarde pour Active IQ Unified Manager sur Windows

Il est recommandé de configurer le volume de stockage des copies Snapshot après les sauvegardes de Unified Manager sur Windows.

.Avant de commencer
Le cluster, la VM de stockage et le volume doivent satisfaire aux exigences suivantes :

* Configuration requise pour le cluster :
+
** ONTAP 9.3 ou version ultérieure doit être installé
** Elle doit se trouver géographiquement proche du serveur Unified Manager
** Il est surveillé par Unified Manager


* Configuration requise pour les machines virtuelles de stockage :
+
** Connectivité iSCSI sur le cluster ONTAP
** Le protocole iSCSI doit être activé pour la machine configurée
** Vous devez disposer d'un volume et d'une LUN dédiés pour la configuration de sauvegarde. Le volume sélectionné ne doit contenir qu'une seule LUN et rien d'autre.
** La taille de la LUN doit être au moins deux fois supérieure à la taille de données prévue pour les 9.9 Active IQ Unified Manager.
+
Cela permet également de définir la même taille pour le volume.

** Assurez-vous que tous les accès en lecture/écriture sont sélectionnés
** Assurez-vous que Superuser Access est défini sur « n'importe quel » dans la politique d'exportation


* Configuration requise pour le volume et les LUN :
+
** Le volume doit être au moins le double de la taille du répertoire de données MySQL Unified Manager.
** Le style de sécurité doit être défini sur Windows
** La stratégie de snapshot local doit être désactivée
** La taille automatique du volume doit être activée
** Le niveau de services de performance doit être défini à une règle avec des IOPS élevées et une faible latence, telles que « extrême »






[[configure-an-ontap-cluster-for-backup-and-restore-in-active-iq-unified-manager]]
== Configurez un cluster ONTAP pour la sauvegarde et la restauration dans Active IQ Unified Manager

Avant de pouvoir sauvegarder et restaurer des Active IQ Unified Manager à l'aide d'une copie Snapshot sur les systèmes ONTAP, vous devez effectuer quelques étapes de préconfiguration sur les clusters.

Vous pouvez configurer le cluster ONTAP à l'aide de l'invite de commandes ou de l'interface utilisateur de System Manager. La configuration du cluster ONTAP implique la configuration des LIFs de données à disponibilité à attribuer en tant que LIFs iSCSI à la VM de stockage. L'étape suivante consiste à configurer une machine virtuelle de stockage iSCSI à l'aide de l'interface utilisateur de System Manager. Vous devrez configurer une route réseau statique pour cette VM de stockage afin de contrôler la façon dont les LIF utilisent le réseau pour le trafic sortant.

[NOTE]
====
Vous devez disposer d'un volume dédié et d'une LUN pour la configuration de sauvegarde. Le volume sélectionné ne doit inclure qu'une seule LUN. La taille de la LUN doit être au moins deux fois supérieure à la taille de données que les Active IQ Unified Manager devraient traiter.

====
Vous devez effectuer la configuration suivante :

.Étapes
. Configurez une machine virtuelle de stockage compatible iSCSI ou utilisez une machine virtuelle de stockage existante dotée de la même configuration.
. Configurer une route réseau pour la VM de stockage configurée
. Configurez un volume de capacité appropriée et une LUN unique à l'intérieur, en veillant à ce que le volume soit dédié uniquement à cette LUN.
+

NOTE: Dans un scénario où la LUN est créée sur System Manager, son annulation peut entraîner la suppression du groupe initiateur et l'échec de la restauration. Pour éviter ce scénario, veillez à ce que la création d'une LUN soit explicitement créée et n'ait pas été supprimée lorsque le mappage de la LUN est annulé.

. Configurez un groupe initiateur sur la machine virtuelle de stockage.
. Configurez un ensemble de ports.
. Intégrez le groupe initiateur avec l'ensemble de ports.
. Mappez la LUN sur le groupe initiateur.




[[configure-a-windows-host-machine-in-active-iq-unified-manager]]
== Configurer une machine hôte Windows dans Active IQ Unified Manager

Vous devez configurer votre serveur hôte Windows avant d'utiliser NetApp Snapshot pour sauvegarder et restaurer Active IQ Unified Manager. Pour démarrer l'initiateur iSCSI Microsoft sur une machine hôte Windows, saisissez « iscsi » dans la barre de recherche et cliquez sur *iSCSI Initiator*.

.Avant de commencer
Vous devez nettoyer toutes les configurations précédentes sur l'ordinateur hôte.

Si vous essayez de démarrer l'initiateur iSCSI lors d'une nouvelle installation de Windows, vous êtes invité à confirmer et, à votre confirmation, la boîte de dialogue Propriétés iSCSI s'affiche. S'il s'agit d'une installation Windows existante, la boîte de dialogue Propriétés iSCSI s'affiche avec une cible inactive ou qui tente de se connecter. Vous devez donc vous assurer que toutes les configurations précédentes sur l'hôte Windows sont supprimées.

.Étapes
. Nettoyez toutes les configurations précédentes sur l'ordinateur hôte.
. Découvrir le portail cible.
. Connectez-vous au portail cible.
. Connectez-vous via un chemins d'accès multiples au portail cible.
. Découvrez les deux LIF.
. Découvrez le LUN configuré sur l'ordinateur Windows en tant que périphérique.
. Configurez la LUN découverte en tant que nouveau lecteur de volume dans Windows.




[[specify-the-destination-location-for-snapshot-copies-on-windows-in-active-iq-unified-manager]]
== Spécifiez l'emplacement de destination des copies Snapshot sous Windows dans Active IQ Unified Manager

Vous devez configurer l'emplacement de destination des copies Snapshot Active IQ Unified Manager sur un volume que vous avez déjà configuré dans l'un de vos clusters ONTAP. Vous devez utiliser la console de maintenance pour définir l'emplacement.

* Vous devez disposer du privilège administrateur pour l'hôte Windows sur lequel Active IQ Unified Manager est installé.
* Vous devez disposer d'un ID utilisateur et d'un mot de passe autorisés pour vous connecter à la console de maintenance du serveur Unified Manager.
* Vous devez disposer de l'adresse IP de gestion de cluster, du nom de la machine virtuelle de stockage, du nom du volume, du nom de LUN, ainsi que du nom d'utilisateur et du mot de passe du système de stockage.
* Vous devez avoir monté le volume en tant que lecteur réseau sur l'hôte Active IQ Unified Manager et vous devez disposer du lecteur de montage.


.Étapes
. À l'aide du shell d'alimentation, connectez-vous à l'adresse IP ou au nom de domaine complet du système Active IQ Unified Manager.
. Connectez-vous au système avec le nom et le mot de passe de l'utilisateur de maintenance (umadmin).
. Saisissez la commande `maintenance_console` Puis appuyez sur entrée.
. Dans la console de maintenance *Menu principal*, saisissez le numéro de l'option *Sauvegarder Restaurer*.
. Entrez le numéro *configurer la sauvegarde NetApp Snapshot*.
. Entrez le nombre de configurations iSCSI.
. Vérifiez les informations que vous devez fournir, puis saisissez le numéro de *entrer les détails de la configuration de sauvegarde*.
. Pour identifier le volume sur lequel la copie Snapshot sera écrite, entrez l'adresse IP de l'interface de gestion du cluster, le nom de la machine virtuelle de stockage, le nom du volume, le nom de la LUN, le nom d'utilisateur et le mot de passe du système de stockage, ainsi que le disque de montage.
. Vérifiez ces informations et entrez `y`.
+
Le système effectue les tâches suivantes :

+
** La VM de stockage est validée
** Le volume est validé
** Le disque de montage et l'état sont validés
** Existence et statut de la LUN
** Lecteur réseau existant
** L'existence de l'espace recommandé (plus de deux fois du répertoire de données mysql) au volume monté est validée
** Chemin LUN correspondant à la LUN dédiée dans le volume
** nom d'igroup
** GUID du volume sur lequel le lecteur réseau est monté
** Initiateur iSCSI utilisé pour communiquer avec ONTAP


. Quittez la console de maintenance et lancez l'interface Active IQ Unified Manager pour créer une planification des copies Snapshot.

