---
permalink: health-checker/task_add_group_actions.html 
sidebar: sidebar 
keywords: add, group, actions 
summary: 'Vous pouvez configurer les actions de groupe que vous souhaitez appliquer aux objets de stockage d"un groupe. La configuration des actions pour un groupe vous permet de gagner du temps, car vous n"avez pas besoin d"ajouter ces actions individuellement à chaque objet.' 
---
= Ajout d'actions de groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les actions de groupe que vous souhaitez appliquer aux objets de stockage d'un groupe. La configuration des actions pour un groupe vous permet de gagner du temps, car vous n'avez pas besoin d'ajouter ces actions individuellement à chaque objet.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Groups*.
. Dans l'onglet *actions de groupe*, cliquez sur *Ajouter*.
. Dans la boîte de dialogue *Ajouter une action de groupe*, entrez un nom et une description pour l'action.
. Dans le menu *Groupe*, sélectionnez un groupe pour lequel vous souhaitez configurer l'action.
. Dans le menu *action Type*, sélectionnez un type d'action.
+
La boîte de dialogue se développe, ce qui vous permet de configurer le type d'action sélectionné avec les paramètres requis.

. Saisissez les valeurs appropriées pour les paramètres requis pour configurer une action de groupe.
. Cliquez sur *Ajouter*.

