---
permalink: health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html 
sidebar: sidebar 
keywords: view, anti-ransomware status, volumes, storage VMs, SVMs 
summary: Vous pouvez afficher la liste de tous les volumes et machines virtuelles de stockage, ainsi que leur état actuel anti-ransomware afin de déterminer si les données de vos volumes sont correctement protégées contre les attaques par ransomware. 
---
= Affichage de l'état anti-ransomware de tous les volumes et machines virtuelles de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la liste de tous les volumes et de toutes les machines virtuelles de stockage (SVM) ainsi que leur statut actuel anti-ransomware afin de déterminer si les données de vos volumes et de vos SVM sont correctement protégées contre les attaques par ransomware.

.Avant de commencer
Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.

Pour plus d'informations sur les différents États de lutte contre les ransomwares, consultez link:https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html#system-manager-procedure["ONTAP : activation d'une protection contre les ransomwares"].



== Afficher les informations de sécurité de tous les volumes avec la détection anti-ransomware

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage* > *volumes*.
. Dans le menu Affichage, sélectionnez *Santé* > *sécurité* > *anti-ransomware*
. Dans la vue *Security: Anti-ransomware*, vous pouvez trier les différents champs ou utiliser le filtre.



NOTE: Une protection contre les ransomwares n'est pas prise en charge pour les volumes hors ligne, les volumes restreints, les volumes SnapLock, les volumes FlexGroup, les volumes FlexCache, Volumes SAN uniquement, volumes des VM de stockage arrêtés, volumes root de VM de stockage, ou volumes de protection des données.



== Affichez les informations de sécurité de toutes les machines virtuelles de stockage avec la détection anti-ransomwares

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *stockage > machines virtuelles de stockage*.
. Sélectionnez *Affichage > sécurité > anti-ransomware*. La liste des SVM avec le statut anti-ransomware est affichée.



NOTE: La surveillance anti-ransomware n'est pas prise en charge sur les machines virtuelles de stockage sur lesquelles le protocole NAS n'est pas activé.
