---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_or_centos_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: 'Vous pouvez restaurer une sauvegarde de vidage de base de données MySQL d"Unified Manager à partir d"une appliance virtuelle vers un système Red Hat Enterprise Linux si vous souhaitez modifier le système d"exploitation hôte sur lequel Unified Manager s"exécute.' 
---
= Migration d'une appliance virtuelle Unified Manager vers un système Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer une sauvegarde de vidage de base de données MySQL d'Unified Manager à partir d'une appliance virtuelle vers un système Red Hat Enterprise Linux si vous souhaitez modifier le système d'exploitation hôte sur lequel Unified Manager s'exécute.

*Ce dont vous aurez besoin*

* Sur l'appliance virtuelle :
+
** Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.
** Vous devez connaître le nom de l'utilisateur de maintenance Unified Manager pour l'opération de restauration.


* Sur le système Linux :
+
** Vous devez avoir installé Unified Manager sur un serveur Linux en suivant les instructions de la section link:../install-linux/concept_install_unified_manager_on_rhel_or_centos.html["Installation de Unified Manager sur des systèmes Linux"].
** La version d'Unified Manager sur ce serveur doit être identique à celle de l'appliance virtuelle à partir de laquelle vous utilisez le fichier de sauvegarde.
** Ne lancez pas l'interface utilisateur et ne configurez aucun cluster, utilisateur ou paramètre d'authentification sur le système Linux après l'installation. Le fichier de sauvegarde remplit ces informations lors du processus de restauration.
** Vous devez disposer des informations d'identification utilisateur root pour l'hôte Linux.




Ces étapes expliquent comment créer un fichier de sauvegarde sur l'appliance virtuelle, copier les fichiers de sauvegarde sur Red Hat Enterprise Linux, puis restaurer la sauvegarde de la base de données sur le nouveau système.

.Étapes
. Sur l'appliance virtuelle, cliquez sur *Management* > *Database Backup*.
. Dans la page *sauvegarde de base de données*, cliquez sur *Paramètres de sauvegarde*.
. Définissez le chemin de sauvegarde sur /jail/support.
. Dans la section planification, sélectionnez *programmé quotidien* et entrez quelques minutes après l'heure actuelle pour que la sauvegarde soit créée sous peu.
. Cliquez sur *appliquer*.
. Attendre quelques heures la génération de la sauvegarde.
+
Une sauvegarde complète peut dépasser 1 Go et peut prendre entre trois et quatre heures.

. Connectez-vous en tant qu'utilisateur root à l'hôte Linux sur lequel Unified Manager est installé et copiez les fichiers de sauvegarde à partir de /support sur l'appliance virtuelle à l'aide de SCP.`root@<rhel_server>:/# scp -r admin@<vapp_server_ip_address>:/support/* .`
+
`root@ocum_rhel-21:/# scp -r admin@10.10.10.10:/support/* .`

+
Assurez-vous d'avoir copié le fichier de sauvegarde .7z et tous les fichiers de référentiel .7z dans le sous-répertoire /database-dumps-repo.

. À l'invite de commande, restaurez la sauvegarde : `um backup restore -f /<backup_file_path>/<backup_file_name>`
+
`um backup restore -f /UM_9.7.N151113.1348_backup_unix_02-12-2019-04-16.7z`

. Une fois l'opération de restauration terminée, connectez-vous à l'interface utilisateur Web de Unified Manager.


Vous devez effectuer les tâches suivantes :

* Générez un nouveau certificat de sécurité HTTPS et redémarrez le serveur Unified Manager.
* Définissez le chemin de sauvegarde sur le paramètre par défaut de votre système Linux (/data/ocum-backup) ou sur un nouveau chemin de votre choix, car il n'y a pas de chemin /jail/support sur le système Linux.
* Reconfigurez les deux côtés de votre connexion Workflow Automation, si WFA est utilisé.
* Reconfigurez les paramètres d'authentification SAML si vous utilisez SAML.


Une fois que vous avez vérifié que tout s'exécute correctement sur votre système Linux, vous pouvez arrêter et supprimer l'appliance virtuelle Unified Manager.
