---
permalink: health-checker/task_add_annotations_dynamically.html 
sidebar: sidebar 
keywords: add, annotations, dynamically 
summary: 'Lorsque vous créez des annotations personnalisées, Unified Manager associe de façon dynamique les clusters, les machines virtuelles de stockage et les volumes avec les annotations à l"aide de règles. Ces règles affectent automatiquement les annotations aux objets de stockage.' 
---
= Ajout dynamique d'annotations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez des annotations personnalisées, Unified Manager associe de façon dynamique les clusters, les machines virtuelles de stockage et les volumes avec les annotations à l'aide de règles. Ces règles affectent automatiquement les annotations aux objets de stockage.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Annotations*.
. Dans la page *Annotations*, cliquez sur *Ajouter une annotation*.
. Dans la boîte de dialogue *Ajouter une annotation*, saisissez un nom et une description pour l'annotation.
. Facultatif : dans la section *valeurs d'annotation*, cliquez sur *Ajouter* pour ajouter des valeurs à l'annotation.
. Cliquez sur *Enregistrer*.

