---
permalink: health-checker/task_add_values_to_annotations.html 
sidebar: sidebar 
keywords: add, values, annotations 
summary: 'Vous pouvez ajouter des valeurs aux annotations, puis associer des objets de stockage à une paire nom-valeur d"annotation spécifique. L"ajout de valeurs aux annotations permet de gérer plus efficacement les objets de stockage.' 
---
= Ajout de valeurs aux annotations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des valeurs aux annotations, puis associer des objets de stockage à une paire nom-valeur d'annotation spécifique. L'ajout de valeurs aux annotations permet de gérer plus efficacement les objets de stockage.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

Vous ne pouvez pas ajouter de valeurs aux annotations prédéfinies.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Annotations*.
. Dans la page *Annotations*, sélectionnez l'annotation à laquelle vous souhaitez ajouter une valeur, puis cliquez sur *Ajouter* dans la section *valeurs*.
. Dans la boîte de dialogue *Ajouter une valeur d'annotation*, spécifiez une valeur pour l'annotation.
+
La valeur que vous spécifiez doit être unique pour l'annotation sélectionnée.

. Cliquez sur *Ajouter*.

