---
permalink: health-checker/task_view_svm_list_and_details.html 
sidebar: sidebar 
keywords: view, storage vm list, details 
summary: 'Depuis le point de vue Health: All Storage VM, vous pouvez surveiller l"inventaire des machines virtuelles de stockage (SVM). Vous pouvez utiliser la page Storage VM / Health pour afficher des informations détaillées sur les SVM surveillés.' 
---
= Affichage de la liste des VM de stockage et des détails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis le point de vue Health: All Storage VM, vous pouvez surveiller l'inventaire des machines virtuelles de stockage (SVM). Vous pouvez utiliser la page Storage VM / Health pour afficher des informations détaillées sur les SVM surveillés.

*Ce dont vous aurez besoin*

Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.

Vous pouvez afficher des détails relatifs aux SVM, comme la capacité, l'efficacité et la configuration d'un SVM. Vous pouvez également afficher des informations sur les périphériques associés et les alertes associées pour ce SVM.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage* > *Storage VM*.
. Choisir l'une des méthodes suivantes pour afficher les détails du SVM :
+
** Pour afficher les informations relatives à l'état de santé de tous les SVM de tous les clusters, dans le menu View, sélectionnez Santé : vue tous les VM de stockage.
** Pour afficher les informations complètes, cliquez sur le nom de la VM de stockage.
+
Vous pouvez également afficher les détails complets en cliquant sur *Afficher les détails* dans la boîte de dialogue Détails minimaux.



. Afficher les objets liés à la SVM en cliquant sur *View Related* dans la boîte de dialogue des détails minimaux.


*Informations connexes*

* link:../health-checker/reference_health_svm_details_page.html["VM de stockage : page Détails de l'état de santé"]
* link:../performance-checker/performance-view-all.html#performance-all-storage-vms-view["Performances : vue de toutes les machines virtuelles de stockage"]
* link:../health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html#view-security-details-of-all-volumes-with-anti-ransomware-detection["Sécurité : vue anti-ransomware"]
* link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Affichage de l'état de sécurité pour les clusters et les VM de stockage"]
* link:../data-protection/reference_relationship_all_relationships_view.html["Relation : vue de toutes les relations"]

