---
permalink: health-checker/task_restore_mysql_db_on_linux.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: 'En cas de perte ou de corruption des données, Unified Manager peut être restauré vers l"état stable précédent avec un minimum de perte de données. Vous pouvez restaurer la base de données Unified Manager sur un système Red Hat Enterprise Linux local ou distant à l"aide de la console de maintenance Unified Manager.' 
---
= Restauration d'une sauvegarde de base de données MySQL sur un système Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de perte ou de corruption des données, Unified Manager peut être restauré vers l'état stable précédent avec un minimum de perte de données. Vous pouvez restaurer la base de données Unified Manager sur un système Red Hat Enterprise Linux local ou distant à l'aide de la console de maintenance Unified Manager.

.Avant de commencer
* Vous devez disposer des informations d'identification utilisateur root pour l'hôte Linux sur lequel Unified Manager est installé.
* Vous devez disposer d'un ID utilisateur et d'un mot de passe autorisés pour vous connecter à la console de maintenance du serveur Unified Manager.
* Vous devez avoir copié le fichier de sauvegarde Unified Manager et le contenu du répertoire du référentiel de base de données sur le système sur lequel vous allez effectuer l'opération de restauration.
+
Il est recommandé de copier le fichier de sauvegarde dans le répertoire par défaut /`data/ocum`-sauvegarde. Les fichiers du référentiel de base de données doivent être copiés sur le système /`database-dumps-repo` sous le sous-répertoire /`ocum-backup` répertoire.

* Les fichiers de sauvegarde doivent être de `.7z` type.


La fonction de restauration est spécifique à la plate-forme et à la version. La restauration d'une sauvegarde Unified Manager ne peut être effectuée que sur la même version de Unified Manager. Vous pouvez restaurer un fichier de sauvegarde Linux ou un fichier de sauvegarde d'appliance virtuelle sur un système Red Hat Enterprise Linux.

[TIP]
====
Si le nom du dossier de sauvegarde contient un espace, vous devez inclure le chemin absolu ou relatif dans des guillemets doubles.

====
.Étapes
. Si vous effectuez une restauration sur un nouveau serveur, une fois l'installation de Unified Manager terminée, ne lancez pas l'interface utilisateur et ne configurez pas les clusters, les utilisateurs ou les paramètres d'authentification. Le fichier de sauvegarde remplit ces informations lors du processus de restauration.
. À l'aide de Secure Shell, connectez-vous à l'adresse IP ou au nom de domaine complet du système Unified Manager.
. Connectez-vous au système avec le nom et le mot de passe de l'utilisateur de maintenance (umadmin).
. Saisissez la commande `maintenance_console` Puis appuyez sur entrée.
. Dans la console de maintenance *Menu principal*, saisissez le numéro de l'option *Sauvegarder Restaurer*.
. Saisissez le numéro de *Restore MySQL Backup*.
. Lorsque vous y êtes invité, entrez le chemin absolu du fichier de sauvegarde.
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
Une fois l'opération de restauration terminée, vous pouvez vous connecter à Unified Manager.



Après la restauration de la sauvegarde, si le serveur OnCommand Workflow Automation ne fonctionne pas, effectuez les opérations suivantes :

. Sur le serveur Workflow Automation, modifiez l'adresse IP du serveur Unified Manager pour qu'elle pointe vers la dernière machine.
. Sur le serveur Unified Manager, réinitialisez le mot de passe de la base de données si l'acquisition échoue à l'étape 1.

