---
permalink: health-checker/task_delete_group_actions.html 
sidebar: sidebar 
keywords: delete, group actions 
summary: 'Vous pouvez supprimer une action de groupe de Unified Manager lorsque l"action de groupe n"est plus nécessaire.' 
---
= Suppression des actions de groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer une action de groupe de Unified Manager lorsque l'action de groupe n'est plus nécessaire.

*Ce dont vous aurez besoin*

Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

Lorsque vous supprimez l'action de groupe pour le seuil d'intégrité du volume, des seuils globaux sont appliqués aux objets de stockage de ce groupe. Les seuils de santé des niveaux objet définis sur l'objet de stockage ne sont pas affectés.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Groups*.
. Dans l'onglet *actions de groupe*, sélectionnez l'action de groupe à supprimer, puis cliquez sur *Supprimer*.
. Dans la boîte de dialogue *Avertissement*, confirmez la suppression en cliquant sur *Oui*.

