---
permalink: health-checker/task_edit_group_actions.html 
sidebar: sidebar 
keywords: edit, group actions 
summary: 'Vous pouvez modifier les paramètres d"action de groupe que vous avez configurés dans Unified Manager, tels que le nom d"action de groupe, la description, le nom de groupe associé et les paramètres du type d"action.' 
---
= Modifier les actions du groupe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'action de groupe que vous avez configurés dans Unified Manager, tels que le nom d'action de groupe, la description, le nom de groupe associé et les paramètres du type d'action.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Groups*.
. Dans l'onglet *actions de groupe*, sélectionnez l'action de groupe à modifier, puis cliquez sur *Modifier*.
. Dans la boîte de dialogue *Modifier l'action de groupe*, modifiez le nom de l'action de groupe, la description, le nom du groupe associé et les paramètres du type d'action, selon les besoins.
. Cliquez sur *Enregistrer*.

