---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: Guide de démarrage rapide pour Unified Manager sur une plateforme VMware vSphere. 
---
= Instructions de démarrage rapide pour les installations VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez télécharger le `.tar` fichier contenant un certificat racine, a `README` fichier et un `OVA` Et déployez Unified Manager en tant qu'appliance virtuelle.



== Configuration minimale requise

* Système d'exploitation : VMware ESXi 6.5, 6.7 et 7.0.x
* RAM : 12 GO
* CPU : 9572 MHz au total
* Espace disque libre : 5 Go (provisionnement fin), 152 Go (provisionnement lourd)


Pour plus de détails sur la configuration requise, reportez-vous à la section link:../install-vapp/concept_requirements_for_installing_unified_manager.html["Conditions requises pour l'installation de Unified Manager"] et link:http://mysupport.netapp.com/matrix["Matrice d'interopérabilité"].



== Installation de Active IQ Unified Manager



=== Téléchargez le programme d'installation

. Téléchargez le `.tar` fichier contenant un certificat racine, a `README` fichier et un `OVA` fichier.
. Enregistrez le fichier dans un répertoire local ou réseau accessible à votre client vSphere.
. Dans le répertoire dans lequel vous avez téléchargé le `.tar` entrez le `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz` commande. + le requis `OVA` un fichier, un certificat racine et un `README` le fichier est décompressé dans le répertoire cible.




=== Vérification de l'intégrité

Vous pouvez vérifier l'intégrité du `OVA` classez-les en suivant les étapes indiquées dans le `README` fichier.



=== Installez Unified Manager

. Dans vSphere client, cliquez sur *fichier > déployer le modèle OVF*.
. Localisez le fichier OVA et utilisez l'assistant pour déployer l'appliance virtuelle sur le serveur ESXi.
. Sur la page Détails de la révision, dans la section Éditeur, le message  `Entrust Code Signing - OVCS2 (Trusted certificate)` confirme l'intégrité du téléchargé `OVA` fichier. Pour le message `Entrust Code Signing - OVCS2 (Invalid certificate)`, Mettez à niveau le serveur VMware vCenter vers 7.0U3E ou une version ultérieure.
. Sur la page Personnaliser le modèle, dans l'onglet Propriétés, remplissez les champs requis pour le type d'installation que vous effectuez :
+
** Pour la configuration statique, entrez les informations requises dans tous les champs. L'ajout d'informations pour le champ *DNS secondaire* n'est pas nécessaire.
** Pour DHCP utilisant IPv4, n'ajoutez aucune information dans aucun champ.
** Pour DHCP utilisant IPv6, cochez la case “Activer l’adressage IPv6 automatique”. N'ajoutez aucune information dans un autre champ.


. Mise sous tension de la machine virtuelle
. Cliquez sur l'onglet Console pour afficher le processus de démarrage initial.
. Configurer le fuseau horaire.
. Entrez un nom d'utilisateur et un mot de passe pour la maintenance Unified Manager.


À la fin de l'installation, les informations de connexion à l'interface utilisateur Web de Unified Manager sont affichées.
