---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html 
sidebar: sidebar 
keywords: restart, unified manager, virtual, machine 
summary: 'Vous pouvez redémarrer la machine virtuelle (VM) Unified Manager à partir de la console de maintenance. Vous devez redémarrer la machine virtuelle après avoir généré un nouveau certificat de sécurité ou en cas de problème avec la machine virtuelle.' 
---
= Redémarrez la machine virtuelle Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez redémarrer la machine virtuelle (VM) Unified Manager à partir de la console de maintenance. Vous devez redémarrer la machine virtuelle après avoir généré un nouveau certificat de sécurité ou en cas de problème avec la machine virtuelle.

.Avant de commencer
* L'appliance virtuelle doit être sous tension.
* Vous devez être connecté à la console de maintenance Unified Manager en tant qu'utilisateur de maintenance.


Vous pouvez également redémarrer la machine virtuelle depuis vSphere en utilisant l'option VMware *Redémarrer l'invité*. Consultez  https://developer.broadcom.com/powercli/latest/vmware.vimautomation.core/commands/restart-vmguest/["l'applet de commande Restart-VMGuest dans la référence de l'applet de commande VMware vSphere PowerCLI de Broadcom."^]

.Étapes
. Dans la console de maintenance, sélectionnez *Configuration du système* > *redémarrer la machine virtuelle*.
. Démarrez l'interface utilisateur Web de Unified Manager à partir de votre navigateur et connectez-vous.

