---
permalink: install-vapp/task_deploy_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: deploy, unified manager, virtual appliance 
summary: 'Après avoir téléchargé le fichier d"installation, vous déployez Unified Manager en tant qu"appliance virtuelle. Utilisez le client Web vSphere pour déployer l"appliance virtuelle sur un serveur ESXi. Lorsque vous déployez l"appliance virtuelle, une machine virtuelle est créée.' 
---
= Déployez l'appliance virtuelle Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir téléchargé le fichier d'installation, vous déployez Unified Manager en tant qu'appliance virtuelle. Utilisez le client Web vSphere pour déployer l'appliance virtuelle sur un serveur ESXi. Lorsque vous déployez l'appliance virtuelle, une machine virtuelle est créée.

.Avant de commencer
Il est recommandé de passer en revue la configuration système requise. Apportez les modifications nécessaires avant de déployer l'appliance virtuelle Unified Manager.

Voir link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Besoins de l'infrastructure virtuelle"].

Voir link:reference_vmware_software_and_installation_requirements.html["Conditions requises pour le logiciel VMware et son installation"].

Si vous utilisez le protocole DHCP (Dynamic Host Configuration Protocol), assurez-vous que le serveur DHCP est disponible et que les configurations de l'adaptateur réseau DHCP et de la machine virtuelle (VM) sont correctes. DHCP est configuré par défaut.

Si vous utilisez une configuration réseau statique, assurez-vous que l'adresse IP n'est pas dupliquée dans le même sous-réseau et que les entrées de serveur DNS appropriées ont été configurées.

Avant de déployer l'appliance virtuelle, procurez-vous les informations suivantes :

* Informations d'identification pour l'accès à VMware vCenter Server et au client Web vSphere
* Adresse IP du serveur ESXi sur lequel vous déployez l'appliance virtuelle Unified Manager
* Détails sur le data Center, tels que la disponibilité de l'espace de stockage
* Si vous n'utilisez pas DHCP, procurez-vous les adresses IPv4 ou IPv6 pour les périphériques réseau auxquels vous prévoyez de vous connecter :
+
** Nom de domaine complet (FQDN) de l'hôte
** Adresse IP de l'hôte
** Masque de réseau
** Adresse IP de la passerelle par défaut
** Adresses DNS principale et secondaire
** Domaines de recherche




Depuis Unified Manager 9.8, VMware Tools a été remplacé par Open VM Tools  `_open-vm-tools_`). Vous n'avez pas besoin d'installer VMware Tools dans le cadre du processus d'installation car `_open-vm-tools_` Est inclus dans le pack d'installation de Unified Manager.

Lors du déploiement de l'appliance virtuelle, un certificat unique auto-signé pour l'accès HTTPS est généré. Lors de l'accès à l'interface utilisateur Web Unified Manager, un avertissement s'affiche dans le navigateur concernant les certificats non fiables.

VMware High Availability pour l'appliance virtuelle Unified Manager est pris en charge.

.Étapes
. Dans vSphere client, cliquez sur *fichier* > *déployer le modèle OVF*.
. Suivez l'assistant de déploiement de modèle OVF pour déployer l'appliance virtuelle Unified Manager.
+
Sur la page Détails de la révision :

+
** Vérifiez les détails de la section Éditeur. Le message *Entrust Code Signing - OVCS2 (certificat de confiance)* confirme l'intégrité du téléchargement `OVA` fichier. + si le message *Entrust Code Signing - OVCS2 (certificat non valide)* s'affiche, mettez à niveau VMware vCenter Server vers 7.0U3E ou une version ultérieure.
+
Sur la page Personnaliser le modèle :

** Laissez tous les champs vides lors de l'utilisation de l'adressage DHCP et IPv4.
** Cochez la case « Activer l'adressage IPv6 automatique » et laissez tous les autres champs vides lors de l'utilisation de l'adressage DHCP et IPv6.
** Si vous souhaitez utiliser une configuration de réseau statique, vous pouvez remplir les champs de cette page et ces paramètres sont appliqués pendant le déploiement. Assurez-vous que l'adresse IP est unique à l'hôte sur lequel elle est déployée, qu'elle n'est pas déjà utilisée et qu'elle possède une entrée DNS valide.


. Une fois l'appliance virtuelle Unified Manager déployée sur le serveur ESXi, mettez la machine virtuelle sous tension en cliquant avec le bouton droit de la souris sur la machine virtuelle, puis en sélectionnant *Power On*.
+
[NOTE]
====
Si l'opération de mise sous tension échoue en raison de ressources insuffisantes, ajoutez des ressources, puis recommencez l'installation.

====
. Cliquez sur l'onglet *Console*.
+
Le processus de démarrage initial prend quelques minutes.

. Pour configurer votre fuseau horaire, entrez votre zone géographique et votre ville ou région comme indiqué dans la fenêtre de la console VM.
+
Toutes les informations de date affichées utilisent le fuseau horaire configuré pour Unified Manager, quel que soit le paramètre de fuseau horaire de vos périphériques gérés. Si vos systèmes de stockage et le serveur de gestion sont configurés avec le même serveur NTP, ils font référence au même instant dans le temps, même s'ils apparaissent différemment. Par exemple, si vous créez une copie Snapshot à l'aide d'un périphérique configuré à l'aide d'un fuseau horaire différent de celui du serveur de gestion, l'horodatage correspond au temps du serveur de gestion.

. Si aucun service DHCP n'est disponible ou s'il y a une erreur dans les détails de la configuration du réseau statique, sélectionnez l'une des options suivantes :
+
[cols="2*"]
|===
| Si vous utilisez... | Alors, procédez comme ça... 


 a| 
DHCP
 a| 
Sélectionnez *Réessayer DHCP*. Si vous envisagez d'utiliser DHCP, assurez-vous qu'il est correctement configuré.

Si vous utilisez un réseau compatible DHCP, les entrées de FQDN et de serveur DNS sont automatiquement données au serveur virtuel. Si DHCP n'est pas correctement configuré avec DNS, le nom d'hôte « UnifiedManager » est automatiquement attribué et associé au certificat de sécurité. Si vous n'avez pas configuré de réseau compatible DHCP, vous devez saisir manuellement les informations de configuration réseau.



 a| 
Une configuration de réseau statique
 a| 
.. Sélectionnez *Entrez les détails de la configuration du réseau statique*.
+
La configuration prend quelques minutes.

.. Confirmez les valeurs que vous avez saisies et sélectionnez *y*.


|===
. À l'invite, entrez un nom d'utilisateur de maintenance, puis cliquez sur *entrée*.
+
Le nom d'utilisateur de maintenance doit commencer par une lettre de a à z, suivie de toute combinaison de -, a à z ou 0 à 9.

. À l'invite, entrez un mot de passe, puis cliquez sur *entrée*.
+
La console de VM affiche l'URL de l'interface utilisateur Web Unified Manager.



Vous pouvez accéder à l'interface utilisateur Web pour effectuer la configuration initiale de Unified Manager, comme décrit dans la link:../config/concept_configure_unified_manager.html["Configuration d'Active IQ Unified Manager en cours"].
