---
permalink: install-vapp/task_download_unified_manager_ova_file.html 
sidebar: sidebar 
keywords: download, unified manager, installation, file 
summary: 'Téléchargez le fichier d"installation Unified Manager depuis le site de support NetApp pour déployer Unified Manager en tant que dispositif virtuel.' 
---
= Téléchargement du fichier d'installation de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Téléchargez le fichier d'installation Unified Manager depuis le site de support NetApp pour déployer Unified Manager en tant que dispositif virtuel.

.Avant de commencer
Vous devez disposer des identifiants de connexion pour le site du support NetApp.

Le fichier d'installation est un `.tar` fichier contenant un certificat racine, a `README` fichier et un `OVA` Fichier contenant le logiciel Unified Manager configuré pour une appliance virtuelle.

.Étapes
. Connectez-vous au site de support NetApp et accédez à la page de téléchargement de Unified Manager :
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de support NetApp"]

. Sélectionnez la version requise de Unified Manager et acceptez le contrat de licence utilisateur final (CLUF).
. Téléchargez et enregistrez `.tar` Fichier pour l'installation de VMware vSphere dans un répertoire local ou un répertoire réseau accessible à votre client vSphere.
. Vérifiez la somme de contrôle pour vous assurer que le logiciel a été correctement téléchargé.
. Accédez au répertoire dans lequel vous avez téléchargé le `.tar` File et entrez la commande suivante dans votre fenêtre de terminal pour développer le bundle Unified Manager :
+
[listing]
----
tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz
----
+
Le requis `OVA` un fichier, un certificat racine et un `README` Le fichier pour Unified Manager est décompressé dans le répertoire cible.

. Vérifier l'intégrité du `OVA` classez-les en suivant les étapes indiquées dans le `README` fichier.

