---
permalink: install-windows/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual infrastructure, hardware, system, requirements, host, connectivity, backups 
summary: 'L"installation de Unified Manager sur une infrastructure virtuelle ou un système physique doit satisfaire aux exigences minimales en matière de mémoire, de processeur et d"espace disque.' 
---
= Configuration minimale requise pour l'infrastructure virtuelle et le système matériel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installation de Unified Manager sur une infrastructure virtuelle ou un système physique doit satisfaire aux exigences minimales en matière de mémoire, de processeur et d'espace disque.

Le tableau suivant affiche les valeurs recommandées pour les ressources mémoire, processeur et espace disque. Ces valeurs ont été qualifiées pour permettre à Unified Manager de satisfaire à des niveaux de performances acceptables.

[cols="2*"]
|===
| Configuration matérielle | Paramètres recommandés 


 a| 
RAM
 a| 
12 Go (minimum requis : 8 Go)



 a| 
Processeurs
 a| 
4 processeurs



 a| 
Capacité du cycle du processeur
 a| 
9572 MHz au total (exigence minimale : 9572 MHz)



 a| 
Espace disque disponible
 a| 
150 Go, où la capacité est allouée comme suit :

* 100 Go d'espace disque pour le répertoire d'installation
* 50 Go d'espace disque pour le répertoire de données MySQL


|===
Unified Manager peut être installé sur des systèmes disposant d'une petite quantité de mémoire, mais les 12 Go recommandés de RAM garantissent qu'un volume suffisant de mémoire est disponible pour des performances optimales de façon à ce que le système puisse prendre en charge des clusters et des objets de stockage supplémentaires à mesure que votre configuration évolue. Vous ne devez pas définir de limites de mémoire sur la machine virtuelle où Unified Manager est déployé, et ne devez pas activer de fonctions (par exemple, l'option de création de bulles) qui empêchent le logiciel d'utiliser la mémoire allouée au système.

De plus, le nombre de nœuds qu'une seule instance de Unified Manager peut contrôler avant d'installer une deuxième instance de Unified Manager est limité. Pour plus d'informations, consultez le _Guide des meilleures pratiques_.

http://["Rapport technique 4621 : Guide des meilleures pratiques de Unified Manager"^]

Les échanges de pages mémoire ont un impact négatif sur les performances du système et de l'application de gestion. La concurrence pour les ressources de processeur indisponibles en raison de l'utilisation globale de l'hôte peut dégrader les performances.



== Exigence pour une utilisation dédiée

Le système physique ou virtuel sur lequel vous installez Unified Manager doit être utilisé exclusivement pour Unified Manager et ne doit pas être partagé avec d'autres applications. D'autres applications peuvent consommer des ressources système et réduire considérablement les performances de Unified Manager.



== Besoins en espace pour les sauvegardes

Si vous prévoyez d'utiliser la fonctionnalité de sauvegarde et de restauration de Unified Manager, allouez de la capacité supplémentaire de sorte que le disque ou le répertoire `data' dispose de 150 Go d'espace. Une sauvegarde peut être écrite sur une destination locale ou sur une destination distante. La meilleure pratique consiste à identifier un emplacement distant externe au système hôte Unified Manager qui dispose d'un espace minimum de 150 Go.



== Conditions requises pour la connectivité hôte

Le système physique ou virtuel sur lequel vous installez Unified Manager doit être configuré de telle manière `ping` nom d'hôte de l'hôte lui-même. Dans le cas d'une configuration IPv6, vérifiez-la `ping6` Le nom d'hôte a réussi pour s'assurer que l'installation d'Unified Manager a réussi.

Vous pouvez utiliser le nom d'hôte (ou l'adresse IP de l'hôte) pour accéder à l'interface utilisateur Web du produit. Si vous avez configuré une adresse IP statique pour votre réseau pendant le déploiement, vous avez désigné un nom pour l'hôte réseau. Si vous avez configuré le réseau à l'aide de DHCP, vous devez obtenir le nom d'hôte du DNS.

Si vous prévoyez d'autoriser les utilisateurs à accéder à Unified Manager à l'aide du nom court au lieu d'utiliser le nom de domaine complet (FQDN) ou l'adresse IP, votre configuration réseau doit résoudre ce nom court sur un FQDN valide.
