---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 'Vous pouvez réinitialiser le mot de passe JBoss spécifique à l"instance défini lors de l"installation. Vous pouvez éventuellement réinitialiser le mot de passe si votre site requiert cette fonctionnalité de sécurité afin de remplacer le paramètre d"installation de Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.' 
---
= Modification du mot de passe JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez réinitialiser le mot de passe JBoss spécifique à l'instance défini lors de l'installation. Vous pouvez éventuellement réinitialiser le mot de passe si votre site requiert cette fonctionnalité de sécurité afin de remplacer le paramètre d'installation de Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.

*Ce dont vous aurez besoin*

* Vous devez disposer des privilèges d'administrateur Windows pour le système sur lequel Unified Manager est installé.
* Vous devez avoir le mot de passe pour l'utilisateur root MySQL.
* Vous devez pouvoir accéder à cet ensemble `password.bat` script dans le répertoire
+
`C:\Program Files\NetApp\essentials\bin`.



.Étapes
. Connectez-vous en tant qu'utilisateur administrateur sur la machine hôte Unified Manager.
. Utilisez la console des services Windows pour arrêter les services Unified Manager suivants :
+
** Service d'acquisition NetApp Active IQ (Ocie-au)
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)


. Lancez le `password.bat` script pour lancer le processus de modification du mot de passe :
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Lorsque vous y êtes invité, saisissez le mot de passe utilisateur root MySQL.
. Lorsque vous y êtes invité, saisissez le nouveau mot de passe utilisateur JBoss, puis saisissez-le à nouveau pour confirmation.
+
Notez que le mot de passe doit comporter entre 8 et 16 caractères et doit contenir au moins un chiffre, un majuscule et des caractères minuscules, et au moins l'un des caractères spéciaux suivants :

+
`+!@%^*-_+=[]:<>.?/~+`

. Une fois le script terminé, démarrez les services Unified Manager à l'aide de la console des services Windows :
+
** Service de serveur de gestion NetApp Active IQ (Oncommandsvc)
** Service d'acquisition NetApp Active IQ (Ocie-au)


. Une fois tous les services démarrés, vous pouvez vous connecter à l'interface utilisateur de Unified Manager.

