---
permalink: install-windows/task_uninstall_third_party_products.html 
sidebar: sidebar 
keywords: MS Visual C++, python, uninstall, uninstalling, 9.18 
summary: Comment désinstaller des produits tiers, notamment Python et Microsoft Visual C++. 
---
= Désinstaller les produits tiers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la mise à niveau d'Unified Manager, vous pouvez désinstaller des produits tiers, tels que Python ou Microsoft Visual C++ 2013. Cette option est facultative.



== Désinstaller Python

.Étapes
. Dans le *panneau de configuration*, sélectionnez *programmes* > *programmes et fonctionnalités*.
. Sélectionnez Python dans la liste des programmes.
. Sélectionnez *Désinstaller ce programme*.  Désinstallez toutes les versions de Python à l'exception de la 3.13.3.  Assurez-vous de conserver la version Python 3.13.3.




== Désinstaller Microsoft Visual C++ 2013

.Étapes
. Dans le *panneau de configuration*, sélectionnez *programmes* > *programmes et fonctionnalités*.
. Sélectionnez *Microsoft Visual C++ 2013* dans la liste des programmes.
. Sélectionnez *Désinstaller ce programme*.

