---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Vous pouvez installer Unified Manager pour surveiller et résoudre les problèmes de capacité, de disponibilité, de performances et de protection du stockage des données. 
---
= Installation de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer Unified Manager pour surveiller et résoudre les problèmes de capacité, de disponibilité, de performances et de protection du stockage des données.

*Ce dont vous aurez besoin*

* Le système sur lequel vous prévoyez d'installer Unified Manager doit répondre aux exigences système et logicielles.
+
Voir link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Configuration matérielle requise"].

+
Voir link:reference_windows_software_and_installation_requirements.html["Conditions requises pour l'installation et le logiciel Windows"].

+
[NOTE]
====
À partir de Unified Manager 9.5, OpenJDK est fourni dans le package d'installation et installé automatiquement. Oracle Java n'est pas pris en charge à partir de Unified Manager 9.5.

====
* Vous devez disposer des privilèges d'administrateur Windows. Assurez-vous que votre nom d'utilisateur ne commence pas par un point d'exclamation ""!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!».
* Un navigateur Web doit être pris en charge.
* Le mot de passe de l'utilisateur de maintenance Unified Manager doit comporter entre 8 et 20 caractères, et contenir des lettres majuscules ou des minuscules, des chiffres et des caractères spéciaux.
* Les caractères spéciaux suivants ne sont pas autorisés dans la chaîne de mot de passe pour l'utilisateur de maintenance ou pour l'utilisateur root MySQL : " ' ` % , = & < > ^ \ / ( ) [ ] ; :
+
Les caractères spéciaux suivants sont autorisés : ~ ! @ # $ * - ? . + { }



.Étapes
. Connectez-vous à Windows à l'aide du compte d'administrateur local par défaut.
. Connectez-vous au site de support NetApp et accédez à la page de téléchargement de Unified Manager :
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de support NetApp"]

. Sélectionnez la version requise de Unified Manager et acceptez le contrat de licence utilisateur final (CLUF).
. Téléchargez le fichier d'installation de Unified Manager Windows dans un répertoire cible du système Windows.
. Accédez au répertoire dans lequel se trouve le fichier d'installation.
. Cliquez avec le bouton droit de la souris et exécutez le fichier exécutable du programme d'installation de Unified Manager (.exe) en tant qu'administrateur.
+
Unified Manager détecte les packages tiers manquants ou pré-installés et les répertorie. Si les modules tiers requis ne sont pas installés sur le système, Unified Manager les installe dans le cadre de l'installation.

. Cliquez sur *Suivant*.
. Entrez le nom d'utilisateur et le mot de passe pour créer l'utilisateur de maintenance.
. Dans l'Assistant connexion à la base de données, saisissez le mot de passe racine MySQL.
. Cliquez sur *Modifier* pour spécifier un nouvel emplacement pour le répertoire d'installation Unified Manager et le répertoire de données MySQL.
+
Si vous ne modifiez pas le répertoire d'installation, Unified Manager est installé dans le répertoire d'installation par défaut.

. Cliquez sur *Suivant*.
. Dans l'assistant prêt à installer Shield, cliquez sur *installer*.
. Une fois l'installation terminée, cliquez sur *Finish*.
. Si un logiciel antivirus actif est installé sur votre système Windows, exclure manuellement les chemins suivants de l'analyse antivirus une fois l'installation terminée :
+
** Répertoire des données Unified Manager
** Répertoire d'installation de Unified Manager
** Répertoire de données MySQL




L'installation crée plusieurs répertoires :

* Répertoire d'installation
+
Il s'agit du répertoire racine de Unified Manager, que vous avez spécifié lors de l'installation. Exemple : `C:\Program Files\NetApp\`

* Répertoire de données MySQL
+
Il s'agit du répertoire dans lequel les bases de données MySQL sont stockées, que vous avez spécifié lors de l'installation. Exemple : `C:\ProgramData\MySQL\MySQLServerData\`

* Répertoire Java
+
Il s'agit du répertoire dans lequel OpenJDK est installé. Exemple : `C:\Program Files\NetApp\JDK\`

* Répertoire des données applicatives Unified Manager (AppDataDir)
+
Il s'agit du répertoire dans lequel toutes les données générées par l'application sont stockées. Cela inclut les journaux, les offres groupées de support, la sauvegarde et toutes les autres données supplémentaires. Exemple : `C:\ProgramData\NetApp\OnCommandAppData\`



Vous pouvez accéder à l'interface utilisateur Web pour effectuer la configuration initiale de Unified Manager, comme décrit dans la link:../config/concept_configure_unified_manager.html["Configuration d'Active IQ Unified Manager en cours"].
