---
permalink: install-windows/task_restart_unified_manager_win.html 
sidebar: sidebar 
keywords: restart, unified manager 
summary: 'Il peut s"avérer nécessaire de redémarrer Unified Manager après avoir apporté des modifications à la configuration.' 
---
= Redémarrage de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il peut s'avérer nécessaire de redémarrer Unified Manager après avoir apporté des modifications à la configuration.

.Avant de commencer
Vous devez disposer des privilèges d'administrateur Windows.

.Étapes
. Connectez-vous à Windows à l'aide du compte d'administrateur local par défaut.
. Arrêtez les services Unified Manager :
+
[cols="2*"]
|===
| Du... | Arrêter les services dans l'ordre suivant... 


 a| 
Ligne de commande
 a| 
.. `sc stop ocie-au`
.. `sc stop Oncommandsvc`




 a| 
Microsoft Service Manager
 a| 
.. Service d'acquisition NetApp Active IQ (Ocie-au)
.. Service de serveur de gestion NetApp Active IQ (Oncommandsvc)


|===
. Démarrez les services Unified Manager :
+
[cols="2*"]
|===
| Du... | Démarrer les services dans l'ordre suivant... 


 a| 
Ligne de commande
 a| 
.. `sc start Oncommandsvc`
.. `sc start ocie-au`




 a| 
Microsoft Service Manager
 a| 
.. Service de serveur de gestion NetApp Active IQ (Oncommandsvc)
.. Service d'acquisition NetApp Active IQ (Ocie-au)


|===

