---
permalink: config/concept_maintenance_console_menu.html 
sidebar: sidebar 
keywords: maintenance, console, menus 
summary: La console de maintenance se compose de différents menus qui vous permettent de maintenir et de gérer des fonctionnalités spéciales et des paramètres de configuration du serveur Unified Manager. 
---
= Menus de la console de maintenance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La console de maintenance se compose de différents menus qui vous permettent de maintenir et de gérer des fonctionnalités spéciales et des paramètres de configuration du serveur Unified Manager.

Selon le système d'exploitation sur lequel Unified Manager est installé, la console de maintenance se compose des menus suivants :

* Mise à niveau de Unified Manager (VMware uniquement)
* Configuration réseau (VMware uniquement)
* Configuration du système (VMware uniquement)
+
.. Support/Diagnostics
.. Réinitialiser le certificat du serveur
.. Régénérer le certificat client
.. Sauvegarde Restauration
.. Fournisseur de données externes
.. Configuration de l'intervalle d'interrogation des performances
.. Désactivez l'authentification SAML
.. Afficher/modifier les ports d'application
.. Configuration du journal de débogage
.. Contrôlez l'accès au port MySQL 3306
.. Quitter




Vous sélectionnez le numéro dans la liste pour accéder à l'option de menu spécifique. Par exemple, pour la sauvegarde et la restauration, vous sélectionnez _4_.
