---
permalink: config/task_set_up_authentication_services.html 
sidebar: sidebar 
keywords: set up, authentication, services 
summary: 'Les services d"authentification permettent l"authentification d"utilisateurs distants ou de groupes distants sur un serveur d"authentification avant de leur donner accès à Unified Manager. Vous pouvez authentifier les utilisateurs en utilisant des services d"authentification prédéfinis (tels qu"Active Directory ou OpenLDAP) ou en configurant votre propre mécanisme d"authentification.' 
---
= Configurer les services d'authentification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les services d'authentification permettent l'authentification d'utilisateurs distants ou de groupes distants sur un serveur d'authentification avant de leur donner accès à Unified Manager. Vous pouvez authentifier les utilisateurs en utilisant des services d'authentification prédéfinis (tels qu'Active Directory ou OpenLDAP) ou en configurant votre propre mécanisme d'authentification.

.Avant de commencer
* Vous devez avoir activé l'authentification à distance.
* Vous devez avoir le rôle Administrateur d'applications.


.Étapes
. Dans le volet de navigation de gauche, cliquez sur *général* > *authentification à distance*.
. Sélectionnez l'un des services d'authentification suivants :
+
[cols="2*"]
|===
| Si vous sélectionnez... | Alors, procédez comme ça... 


 a| 
Active Directory
 a| 
.. Entrez le nom et le mot de passe de l'administrateur.
.. Spécifiez le nom distinctif de base du serveur d'authentification.
+
Par exemple, si le nom de domaine du serveur d'authentification est +ou@domain.com+, le nom distinctif de base est *cn=ou,dc=domaine,dc=com*.





 a| 
OpenLDAP
 a| 
.. Entrez le nom distinctif de liaison et le mot de passe de liaison.
.. Spécifiez le nom distinctif de base du serveur d'authentification.
+
Par exemple, si le nom de domaine du serveur d'authentification est +ou@domain.com+, le nom distinctif de base est *cn=ou,dc=domaine,dc=com*.





 a| 
Autres
 a| 
.. Entrez le nom distinctif de liaison et le mot de passe de liaison.
.. Spécifiez le nom distinctif de base du serveur d'authentification.
+
Par exemple, si le nom de domaine du serveur d'authentification est +ou@domain.com+, le nom distinctif de base est *cn=ou,dc=domaine,dc=com*.

.. Spécifiez la version du protocole LDAP prise en charge par le serveur d'authentification.
.. Entrez le nom d'utilisateur, l'appartenance au groupe, le groupe d'utilisateurs et les attributs de membre.


|===
+
[NOTE]
====
Si vous souhaitez modifier le service d'authentification, vous devez supprimer tout serveur d'authentification existant, puis ajouter de nouveaux serveurs d'authentification.

====
. Cliquez sur *Enregistrer*.

