---
permalink: config/task_change_maintenance_user_password_on_windows.html 
sidebar: sidebar 
keywords: change, maintenance, user, password, windows 
summary: 'Vous pouvez modifier le mot de passe utilisateur responsable de la maintenance d"Unified Manager si nécessaire.' 
---
= Modifier le mot de passe de l'utilisateur de maintenance sous Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe utilisateur responsable de la maintenance d'Unified Manager si nécessaire.

.Étapes
. Dans la page de connexion à l'interface utilisateur Web de Unified Manager, cliquez sur *Mot de passe oublié*.
+
Une page s'affiche et vous demande le nom de l'utilisateur dont vous souhaitez réinitialiser le mot de passe.

. Entrez le nom d'utilisateur et cliquez sur *Envoyer*.
+
Un e-mail contenant un lien pour réinitialiser le mot de passe est envoyé à l'adresse e-mail définie pour ce nom d'utilisateur.

. Cliquez sur le lien *reset mot de passe* dans l'e-mail et définissez le nouveau mot de passe.
. Revenez à l'interface utilisateur Web et connectez-vous à Unified Manager à l'aide du nouveau mot de passe.

