---
permalink: config/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux, host 
summary: 'Si vous avez alloué un espace disque insuffisant à l" `/opt/netapp/data` Répertoire pour prendre en charge Unified Manager lorsque vous configurez l"hôte Linux à l"origine, puis que Unified Manager a été installé, vous pouvez ajouter de l"espace disque après l"installation en augmentant l"espace disque sur le `/opt/netapp/data` répertoire.' 
---
= Ajout d'espace au répertoire de données de l'hôte Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez alloué un espace disque insuffisant à l' `/opt/netapp/data` Répertoire pour prendre en charge Unified Manager lorsque vous configurez l'hôte Linux à l'origine, puis que Unified Manager a été installé, vous pouvez ajouter de l'espace disque après l'installation en augmentant l'espace disque sur le `/opt/netapp/data` répertoire.

*Ce dont vous aurez besoin*

Vous devez disposer d'un accès utilisateur root à la machine Red Hat Enterprise Linux sur laquelle Unified Manager est installé.

Nous vous recommandons de sauvegarder la base de données Unified Manager avant d'augmenter la taille du répertoire de données.

.Étapes
. Connectez-vous en tant qu'utilisateur root à la machine Linux sur laquelle vous souhaitez ajouter de l'espace disque.
. Arrêtez le service Unified Manager et le logiciel MySQL associé dans l'ordre indiqué :
+
`systemctl stop ocieau ocie mysqld`

. Créer un dossier de sauvegarde temporaire (par exemple, `/backup-data`) avec suffisamment d'espace disque pour contenir les données dans le courant `/opt/netapp/data` répertoire.
. Copie de la configuration de contenu et de privilège de l'existant `/opt/netapp/data` répertoire vers le répertoire de données de sauvegarde :
+
`cp -arp /opt/netapp/data/* /backup-data`

. Si se Linux est activé :
+
.. Obtenir le type se Linux pour les dossiers existants `/opt/netapp/data` dossier :
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}' | awk -F: '{print $3}' | head -1`

+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Lancer la commande chcon pour définir le type se Linux du répertoire de sauvegarde :
+
`chcon -R --type=mysqld_db_t /backup-data`



. Retirez le contenu du `/opt/netapp/data` répertoire :
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Développez la taille du `/opt/netapp/data` Répertoire d'au moins 150 Go via les commandes LVM ou en ajoutant des disques supplémentaires.
+
[NOTE]
====
Si vous avez créé `/opt/netapp/data` a partir d'un disque, n'essayez pas de monter `/opt/netapp/data` En tant que partage NFS ou CIFS. Car, dans ce cas, si vous essayez d'étendre l'espace disque, certaines commandes LVM, telles que `resize` et `extend` ne fonctionne peut-être pas comme prévu.

====
. Confirmez que le `/opt/netapp/data` le propriétaire du répertoire (mysql) et le groupe (root) sont inchangés:
+
`ls -ltr /opt/netapp/ | grep data`

+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Si se Linux est activé, confirmez que le contexte de l' `/opt/netapp/data` le répertoire est toujours défini sur mysqld_db_t:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Supprimez le fichier abc pour que ce fichier externe ne provoque pas d'erreur dans la base de données à l'avenir.
. Copiez le contenu des données de sauvegarde vers le contenu étendu `/opt/netapp/data` répertoire :
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Si se Linux est activé, exécutez la commande suivante :
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Démarrez le service MySQL :
+
`systemctl start mysqld`

. Une fois le service MySQL démarré, démarrer les services ocie et ocieau dans l'ordre indiqué:
+
`systemctl start ocie ocieau`

. Une fois tous les services démarrés, supprimez le dossier de sauvegarde `/backup-data`:
+
`rm -rf /backup-data`


