---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: 'Vous pouvez configurer Unified Manager pour qu"il envoie des notifications d"alerte lorsqu"un événement est généré ou lorsqu"un événement est affecté à un utilisateur. Vous pouvez configurer le serveur SMTP utilisé pour envoyer l"alerte et définir différents mécanismes de notification, par exemple, des notifications d"alerte peuvent être envoyées en tant qu"e-mails ou interruptions SNMP.' 
---
= Configurer les paramètres de notification d'événements
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer Unified Manager pour qu'il envoie des notifications d'alerte lorsqu'un événement est généré ou lorsqu'un événement est affecté à un utilisateur. Vous pouvez configurer le serveur SMTP utilisé pour envoyer l'alerte et définir différents mécanismes de notification, par exemple, des notifications d'alerte peuvent être envoyées en tant qu'e-mails ou interruptions SNMP.

.Avant de commencer
Vous devez disposer des informations suivantes :

* Adresse e-mail à partir de laquelle la notification d'alerte est envoyée
+
L'adresse e-mail apparaît dans le champ « de » des notifications d'alerte envoyées. Si l'e-mail ne peut pas être livré pour une raison quelconque, cette adresse e-mail est également utilisée comme destinataire pour le courrier non livrable.

* Le nom d'hôte du serveur SMTP ainsi que le nom d'utilisateur et le mot de passe pour accéder au serveur
* Nom d'hôte ou adresse IP de l'hôte de destination de déroutement qui recevra l'interruption SNMP, ainsi que la version SNMP, le port d'interruption sortant, la communauté et d'autres valeurs de configuration SNMP requises
+
Pour spécifier plusieurs destinations d'interruption, séparez chaque hôte par une virgule. Dans ce cas, tous les autres paramètres SNMP, tels que la version et le port d'interruption sortante, doivent être identiques pour tous les hôtes de la liste.



Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *général* > *Notifications*.
. Dans la page Notifications, configurez les paramètres appropriés.
+
*Notes:*

+
** Si l'adresse de expéditeur est pré-remplie avec l'adresse « + ActiveIQUnifiedManager@localhost.com+ », vous devez la remplacer par une adresse e-mail réelle et opérationnelle pour vous assurer que toutes les notifications par e-mail ont été envoyées correctement.
** Si le nom d'hôte du serveur SMTP ne peut pas être résolu, vous pouvez spécifier l'adresse IP (IPv4 ou IPv6) du serveur SMTP au lieu du nom d'hôte.


. Cliquez sur *Enregistrer*.
. Si vous avez sélectionné l'option *Use STARTTLS* ou *use SSL*, une page de certificat s'affiche après avoir cliqué sur le bouton *Save*. Vérifiez les détails du certificat et acceptez le certificat pour enregistrer les paramètres de notification.
+
Vous pouvez cliquer sur le bouton *Afficher les détails du certificat* pour afficher les détails du certificat. Si le certificat existant est expiré, décochez la case *utiliser STARTTLS* ou *utiliser SSL*, enregistrez les paramètres de notification, puis cochez de nouveau la case *utiliser STARTTLS* ou *utiliser SSL* pour afficher un nouveau certificat.


