---
permalink: config/task_download_an_https_certificate_sign_request_ocf.html 
sidebar: sidebar 
keywords: download, https, certificate, signing, request 
summary: 'Vous pouvez télécharger une demande de signature de certification pour le certificat de sécurité HTTPS actuel afin de pouvoir fournir le fichier à une autorité de certification à signer. Un certificat signé par une autorité de certification contribue à prévenir les attaques de l"homme du milieu et offre une meilleure protection contre la sécurité qu"un certificat auto-signé.' 
---
= Téléchargement d'une demande de signature de certificat HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez télécharger une demande de signature de certification pour le certificat de sécurité HTTPS actuel afin de pouvoir fournir le fichier à une autorité de certification à signer. Un certificat signé par une autorité de certification contribue à prévenir les attaques de l'homme du milieu et offre une meilleure protection contre la sécurité qu'un certificat auto-signé.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *général* > *certificat HTTPS*.
. Cliquez sur *Télécharger demande de signature de certificat HTTPS*.
. Enregistrez le `<hostname>.csr` fichier.


Vous pouvez fournir le fichier à une autorité de certification pour signer, puis installer le certificat signé.
