---
permalink: config/task_add_space_to_data_disk_of_windows_server.html 
sidebar: sidebar 
keywords: add, space, logical, drive, microsoft windows server 
summary: 'Si vous devez augmenter la quantité d"espace disque pour la base de données Unified Manager, vous pouvez ajouter de la capacité au lecteur logique sur lequel Unified Manager est installé.' 
---
= Ajout d'espace au lecteur logique du serveur Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous devez augmenter la quantité d'espace disque pour la base de données Unified Manager, vous pouvez ajouter de la capacité au lecteur logique sur lequel Unified Manager est installé.

*Ce dont vous aurez besoin*

Vous devez disposer des privilèges d'administrateur Windows.

Nous vous recommandons de sauvegarder la base de données Unified Manager avant d'ajouter de l'espace disque.

.Étapes
. Connectez-vous en tant qu'administrateur au serveur Windows sur lequel vous souhaitez ajouter de l'espace disque.
. Suivez l'étape qui correspond à la méthode que vous souhaitez utiliser pour ajouter de l'espace :
+
[cols="2*"]
|===
| Option | Description 


 a| 
Sur un serveur physique, ajoutez de la capacité au lecteur logique sur lequel le serveur Unified Manager est installé.
 a| 
Suivez les étapes de la rubrique Microsoft :

https://["Extension d'un volume de base"]



 a| 
Sur un serveur physique, ajoutez un disque dur.
 a| 
Suivez les étapes de la rubrique Microsoft :

https://["Ajout de disques durs"]



 a| 
Sur une machine virtuelle, augmentez la taille d'une partition de disque.
 a| 
Suivez les étapes du sujet VMware :

https://["Augmentation de la taille d'une partition de disque"]

|===

