---
permalink: config/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 'Vous pouvez ajouter un cluster à Active IQ Unified Manager afin de pouvoir contrôler le cluster. Il est donc possible d"obtenir des informations sur le cluster, notamment son état, sa capacité, ses performances et sa configuration, afin de trouver et de résoudre tous les problèmes potentiels.' 
---
= Ajouter des clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter un cluster à Active IQ Unified Manager afin de pouvoir contrôler le cluster. Il est donc possible d'obtenir des informations sur le cluster, notamment son état, sa capacité, ses performances et sa configuration, afin de trouver et de résoudre tous les problèmes potentiels.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez disposer des informations suivantes :
+
** Unified Manager prend en charge les clusters ONTAP sur site, ONTAP Select et Cloud Volumes ONTAP.
** Nom d'hôte ou adresse IP de gestion du cluster
+
Le nom d'hôte est le FQDN ou le nom court que Unified Manager utilise pour se connecter au cluster. Le nom d'hôte doit être résolu sur l'adresse IP de gestion du cluster.

+
L'adresse IP de gestion du cluster doit être la LIF de gestion du cluster du serveur virtuel de stockage administratif (SVM). Si vous utilisez une LIF node-management, l'opération échoue.

** Le cluster doit exécuter la version 9.1 du logiciel ONTAP ou une version ultérieure.
** Nom d'utilisateur et mot de passe de l'administrateur ONTAP
+
Ce compte doit avoir le rôle _admin_ avec accès à l'application défini sur _ontapi_, _console_ et _http_.

** Le numéro de port à connecter au cluster via le protocole HTTPS (en général le port 443)
** Vous disposez des certificats requis :
+
*Certificat SSL (HTTPS)* : ce certificat appartient à Unified Manager. Un certificat SSL (HTTPS) auto-signé par défaut est généré avec une nouvelle installation de Unified Manager. NetApp vous recommande de le mettre à niveau vers un certificat signé par une autorité de certification pour une meilleure sécurité. Si le certificat du serveur expire, vous devez le régénérer et redémarrer Unified Manager pour que les services incorporent le nouveau certificat. Pour plus d'informations sur la régénération du certificat SSL, reportez-vous à la section link:../config/task_generate_an_https_security_certificate_ocf.html["Génération d'un certificat de sécurité HTTPS"].

+
*Certificat EMS* : ce certificat appartient à Unified Manager. Il est utilisé lors de l'authentification pour les notifications EMS reçues de ONTAP.

+
*Certificats de communication mutuelle TLS* : utilisés pendant la communication mutuelle TLS entre Unified Manager et ONTAP. L'authentification basée sur le certificat est activée pour un cluster, sur la version ONTAP utilisée. Si le cluster exécutant la version ONTAP est inférieur au 9.5, l'authentification basée sur certificat n'est pas activée.

+
L'authentification basée sur des certificats n'est pas activée automatiquement sur un cluster si vous mettez à jour une version antérieure d'Unified Manager. Cependant, vous pouvez l'activer en modifiant et en enregistrant les détails du cluster. Si le certificat expire, vous devez le régénérer pour incorporer le nouveau certificat. Pour plus d'informations sur l'affichage et la régénération du certificat, reportez-vous à la section link:../storage-mgmt/task_edit_clusters.html["Modification des clusters"].

+
[NOTE]
====
*** Vous pouvez ajouter un cluster depuis l'interface utilisateur Web et l'authentification basée sur certificat est automatiquement activée.
*** Vous pouvez ajouter un cluster via l'interface de ligne de commandes Unified Manager ; l'authentification basée sur des certificats n'est pas activée par défaut. Si vous ajoutez un cluster via l'interface de ligne de commande d'Unified Manager, vous devez le modifier à l'aide de l'interface utilisateur d'Unified Manager. Vous pouvez voir link:https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_supported_unified_manager_cli_commands.html["Commandes CLI Unified Manager prises en charge"] Pour ajouter un cluster à l'aide de l'interface de ligne de commande Unified Manager.
*** Si l'authentification basée sur les certificats est activée pour un cluster et que vous effectuez la sauvegarde de Unified Manager à partir d'un serveur et que vous effectuez une restauration vers un autre serveur Unified Manager où le nom d'hôte ou l'adresse IP sont modifiés, la surveillance du cluster peut échouer. Pour éviter la défaillance, modifiez et enregistrez les détails du cluster. Pour plus d'informations sur la modification des détails du cluster, reportez-vous à la section link:../storage-mgmt/task_edit_clusters.html["Modification des clusters"].


====
+
*Certificats de cluster* : ce certificat appartient à ONTAP. Vous ne pouvez pas ajouter de cluster à Unified Manager avec un certificat expiré et si le certificat a déjà expiré, vous devez le régénérer avant d'ajouter le cluster. Pour plus d'informations sur la génération du certificat, consultez l'article de la base de connaissances https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["Comment renouveler un certificat auto-signé ONTAP dans l'interface utilisateur de System Manager"^].



* L'espace requis doit être adéquat sur le serveur Unified Manager. Vous ne pouvez pas ajouter un cluster au serveur lorsque plus de 90 % d'espace dans le répertoire de base de données est déjà utilisé.


Dans le cas d'une configuration MetroCluster, vous devez ajouter les clusters locaux et distants, et les clusters doivent être configurés correctement.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage Management* > *Cluster Setup*.
. Sur la page Configuration du cluster, cliquez sur *Ajouter*.
. Dans la boîte de dialogue Ajouter un cluster, spécifiez les valeurs requises, telles que le nom d'hôte ou l'adresse IP du cluster, le nom d'utilisateur, le mot de passe et le numéro de port.
+
Vous pouvez modifier l'adresse IP de gestion du cluster d'IPv6 au format IPv4 ou d'IPv4 à IPv6. La nouvelle adresse IP est indiquée dans la grille du cluster et la page de configuration du cluster une fois le cycle de surveillance suivant terminé.

. Cliquez sur *soumettre*.
. Dans la boîte de dialogue Autoriser l'hôte, cliquez sur *Afficher le certificat* pour afficher les informations de certificat sur le cluster.
. Cliquez sur *Oui*.
+
Une fois les informations de cluster enregistrées, vous pouvez afficher le certificat pour les communications TLS mutuelles pour un cluster.

+
Si l'authentification basée sur le certificat n'est pas activée, Unified Manager vérifie le certificat uniquement lorsque le cluster est ajouté au départ. Unified Manager ne vérifie pas le certificat pour chaque appel d'API au ONTAP.



Une fois que tous les objets d'un nouveau cluster sont découverts, Unified Manager commence à collecter les données d'historique de performances des 15 jours précédents. Ces statistiques sont collectées à l'aide de la fonctionnalité de collecte de continuité des données. Cette fonctionnalité fournit des informations de performance sur plus de deux semaines pour un cluster immédiatement après son ajout. Une fois le cycle de collecte de continuité des données terminé, les données en temps réel des performances du cluster sont collectées, par défaut, toutes les cinq minutes.

[NOTE]
====
Étant donné que la collecte de données de performances sur 15 jours consomme beaucoup de ressources CPU, il est conseillé d'échelonner l'ajout de nouveaux clusters pour que les sondages de collecte de la continuité des données ne s'exécutent pas simultanément sur un trop grand nombre de clusters. En outre, si vous redémarrez Unified Manager pendant la période de collecte de la continuité des données, la collecte sera interrompue et vous verrez des écarts dans les graphiques de performances pour les périodes manquantes.

====
[TIP]
====
Si vous recevez un message d'erreur que vous ne pouvez pas ajouter le cluster, vérifiez si les horloges sur les deux systèmes ne sont pas synchronisées et que la date de début du certificat HTTPS Unified Manager est postérieure à celle du cluster. Vous devez vous assurer que les horloges sont synchronisées à l'aide du protocole NTP ou d'un service similaire.

====
*Informations connexes*

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["L'installation d'une autorité de certification a signé et renvoyé un certificat HTTPS"]
