---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: 'Le système Linux sur lequel vous installez Unified Manager nécessite des versions spécifiques du système d"exploitation et des logiciels de prise en charge.' 
---
= Conditions requises pour l'installation et le logiciel Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système Linux sur lequel vous installez Unified Manager nécessite des versions spécifiques du système d'exploitation et des logiciels de prise en charge.



== Logiciel de système d'exploitation

Le système Linux doit disposer des versions suivantes du système d'exploitation et des logiciels de support installés :

* Red Hat Enterprise Linux versions 8.x et 9.4, basée sur l'architecture x86_64.


Consultez la matrice d'interopérabilité pour obtenir la liste complète et la plus récente des versions de Red Hat Enterprise Linux prises en charge.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

Le serveur doit être dédié à l'exécution de Unified Manager. Aucune autre application ne doit être installée sur le serveur. Il est possible que le scanner de vulnérabilité comme Qualys soit installé sur votre système Linux en raison des réglementations de l'entreprise. Vous devez désactiver l'analyse des vulnérabilités avant d'installer Unified Manager pour empêcher l'installation de échouer.


NOTE: Les scanneurs de vulnérabilité (tels que Qualys) peuvent entraîner une utilisation élevée du CPU lors de l'analyse de la machine virtuelle en interne (où Unified Manager et l'analyse de vulnérabilité sont installés sur la même machine virtuelle) ou en externe (où Unified Manager et l'analyse des vulnérabilités sont installés sur deux serveurs différents et que l'analyse des vulnérabilités analyse la machine virtuelle sur laquelle Unified Manager est installé). Ce problème entraîne souvent une non-réponse de la machine virtuelle et affecte les services Unified Manager. Par conséquent, NetApp recommande de désactiver l'analyse des vulnérabilités sur la machine virtuelle sur laquelle Unified Manager est installé. Si la désactivation du scanner n'est pas une option, scanner la machine virtuelle pendant les heures non ouvrables et redémarrer les services une fois l'analyse terminée.



== Logiciels tiers

Unified Manager est déployé sur un serveur Web WildFly. WildFly 26.1.3 est fourni et configuré avec Unified Manager.

Les packages tiers suivants sont requis, mais ils ne sont pas inclus avec Unified Manager. Ces modules sont automatiquement installés par le `yum` pendant l'installation, à condition que vous ayez configuré les référentiels comme indiqué dans les sections suivantes.

* MySQL Community Edition version 8.4.4 (à partir du référentiel MySQL)
* OpenJDK version 11.0.25 (à partir du référentiel Red Hat Extra Enterprise Linux Server)
* Python 3.9.x (depuis le référentiel Red Hat Extra Enterprise Linux Server)
* P7zip version 16.02 ou ultérieure (à partir du référentiel Red Hat Extra Packages for Enterprise Linux)


[NOTE]
====
Vous devez arrêter une instance en cours d'exécution de Unified Manager avant de mettre à niveau un logiciel tiers. Une fois l'installation du logiciel tiers terminée, vous pouvez redémarrer Unified Manager.

====


== Exigences d'autorisation utilisateur

L'installation de Unified Manager sur un système Linux peut être effectuée par l'utilisateur root ou par des utilisateurs non-root à l'aide de l' `sudo` commande.

En outre, l'installation par défaut de Unified Manager inclut l'utilisateur umadmin (utilisateur de maintenance par défaut) et l'utilisateur jboss dans les fichiers sudoers (`ocum_sudoers`et `ocie_sudoers`) dans le `/etc/sudoers.d/` répertoire. Si vous supprimez ce contenu de votre environnement en raison de stratégies de sécurité ou en raison d'un outil de surveillance de la sécurité, vous devez le réintégrer. Vous devez conserver la configuration des sudoers car certaines opérations Unified Manager nécessitent ces privilèges de sudo.



== Conditions requises pour l'installation

Les meilleures pratiques d'installation de Red Hat Enterprise Linux et des référentiels associés sur votre système sont répertoriées ci-dessous. Les systèmes installés ou configurés différemment, ou déployés hors site (dans le cloud) peuvent nécessiter des étapes supplémentaires et Unified Manager peut ne pas s'exécuter correctement dans de tels déploiements.

* Vous devez installer Red Hat Enterprise Linux conformément aux meilleures pratiques de Red Hat, et vous devez sélectionner les options par défaut suivantes, qui nécessitent la sélection de l'environnement de base « serveur avec interface utilisateur graphique ».
* Lors de l'installation d'Unified Manager sur Red Hat Enterprise Linux, le système doit avoir accès au référentiel approprié pour que le programme d'installation puisse accéder à toutes les dépendances logicielles requises et les installer.
* Pour le `yum` Programme d'installation pour rechercher des logiciels dépendants dans les référentiels Red Hat Enterprise Linux, vous devez avoir enregistré le système lors de l'installation de Red Hat Enterprise Linux ou par la suite en utilisant un abonnement Red Hat valide.
+
Pour plus d'informations sur le Gestionnaire d'abonnement Red Hat, reportez-vous à la documentation Red Hat.

* Vous devez activer le référentiel des progiciels supplémentaires pour Enterprise Linux (EPEL) pour installer correctement les utilitaires tiers requis sur votre système.
+
Si le référentiel EPEL n'est pas configuré sur votre système, vous devez télécharger et configurer manuellement le référentiel.

+
Voir link:task_manually_configure_epel_repository.html["Configuration manuelle du référentiel EPEL"].

* Si la version correcte de MySQL n'est pas installée, vous devez activer le référentiel MySQL pour installer correctement le logiciel MySQL sur votre système.
+
Si le référentiel MySQL n'est pas configuré sur votre système, vous devez télécharger et configurer manuellement le référentiel.

+
Voir link:task_manually_configure_mysql_repository.html["Configuration manuelle du référentiel MySQL"].

* Vous devez installer une seule version de Java sur votre hôte Unified Manager ; sinon, le système peut ne pas être en mesure de déterminer quelle version utiliser. Voir https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Après la mise à jour de Java sur l'hôte Active IQ Unified Manager, les services ne démarrent pas"].


Si votre système n'a pas accès à Internet et que les référentiels ne sont pas mis en miroir à partir d'un système connecté à Internet vers un système non connecté, vous devez suivre les instructions d'installation pour déterminer les dépendances logicielles externes de votre système. Vous pouvez ensuite télécharger le logiciel requis sur le système connecté à Internet et copier les `.rpm` fichiers sur le système sur lequel vous prévoyez d'installer Unified Manager. Pour télécharger les artéfacts et les packages, vous devez utiliser `yum install` la commande. Vous devez vous assurer que les deux systèmes exécutent la même version de système d'exploitation et que la licence d'abonnement est destinée à Red Hat Enterprise Linux approprié.

[NOTE]
====
Vous ne devez pas installer les logiciels tiers requis à partir d'autres référentiels que ceux répertoriés ici. Les logiciels installés à partir des référentiels Red Hat sont conçus explicitement pour Red Hat Enterprise Linux et respectent les meilleures pratiques Red Hat (mises en page des répertoires, autorisations, etc.). Il est possible que les logiciels provenant d'autres emplacements ne respectent pas ces directives, ce qui peut entraîner l'échec de l'installation de Unified Manager ou risque de provoquer des problèmes lors des mises à niveau futures.

====


== Orifice 443 requis

Les images génériques de Red Hat Enterprise Linux peuvent bloquer l'accès externe au port 443. En raison de cette restriction, il se peut que vous ne puissiez pas vous connecter à l'interface utilisateur Web de l'administrateur après avoir installé Unified Manager. L'exécution de la commande suivante permet d'accéder au port 443 pour tous les utilisateurs et applications externes sur un système Red Hat Enterprise Linux générique.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

Vous devez installer Red Hat Enterprise Linux avec l'environnement de base « serveur avec interface utilisateur graphique ». Il fournit les commandes utilisées par les instructions d'installation de Unified Manager. D'autres environnements de base peuvent nécessiter l'installation de commandes supplémentaires pour valider ou terminer l'installation. Si le `firewall-cmd` n'est pas disponible sur votre système, vous devez l'installer en exécutant la commande suivante :

`# sudo yum install firewalld`

Contactez votre service INFORMATIQUE avant d'exécuter les commandes pour voir si vos stratégies de sécurité nécessitent une procédure différente.

[NOTE]
====
THP (transparent énorme pages) doit être désactivé sur les systèmes Red Hat. Lorsqu'il est activé, dans certains cas, Unified Manager peut être arrêté lorsque certains processus consomment trop de mémoire et sont arrêtés.

====