---
permalink: install-linux/task_upgrade_host_os_from_rhel_6_x_to_7_x.html 
sidebar: sidebar 
keywords: upgrade, host OS, red hat enterprise, linux 7.x, 8.x 
summary: 'Si vous avez déjà installé Unified Manager sur un système Red Hat Enterprise Linux 7.x et que vous devez effectuer une mise à niveau vers Red Hat Enterprise Linux 8.x, vous devez suivre l"une des procédures répertoriées dans cette rubrique. Dans les deux cas, vous devez créer une sauvegarde de Unified Manager sur le système Red Hat Enterprise Linux 7.x, puis restaurer la sauvegarde sur un système Red Hat Enterprise Linux 8.x.' 
---
= Mise à niveau du système d'exploitation hôte de Red Hat Enterprise Linux 7.x vers 8.x.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez déjà installé Unified Manager sur un système Red Hat Enterprise Linux 7.x et que vous devez effectuer une mise à niveau vers Red Hat Enterprise Linux 8.x, vous devez suivre l'une des procédures répertoriées dans cette rubrique. Dans les deux cas, vous devez créer une sauvegarde de Unified Manager sur le système Red Hat Enterprise Linux 7.x, puis restaurer la sauvegarde sur un système Red Hat Enterprise Linux 8.x.

La différence entre les deux options répertoriées ci-dessous réside dans le fait que, dans un cas, vous effectuez la restauration de Unified Manager sur un nouveau serveur 8.x, et dans l'autre cas, vous effectuez l'opération de restauration sur le même serveur.

Dans la mesure où cette tâche nécessite la création d'une sauvegarde de Unified Manager sur le système Red Hat Enterprise Linux 7.x, vous devez créer la sauvegarde uniquement lorsque vous êtes prêt à terminer l'intégralité du processus de mise à niveau afin que Unified Manager soit hors ligne pendant une période très courte. Des lacunes dans les données collectées apparaissent dans l'interface utilisateur Unified Manager pendant la période pendant laquelle le système Red Hat Enterprise Linux 7.x est arrêté et avant le démarrage du nouveau système Red Hat Enterprise Linux 8.x.

Reportez-vous à l'aide en ligne de _Active IQ Unified Manager_ si vous avez besoin de consulter des instructions détaillées pour les processus de sauvegarde et de restauration.

*Mise à niveau du système d'exploitation hôte à l'aide d'un nouveau serveur*

Procédez comme suit si vous disposez d'un système de rechange sur lequel vous pouvez installer le logiciel Red Hat Enterprise Linux 8.x afin de pouvoir effectuer la restauration Unified Manager sur ce système alors que le système Red Hat Enterprise Linux 7.x est toujours disponible.

. Installez et configurez un nouveau serveur avec le logiciel Red Hat Enterprise Linux 8.x.
+
Voir link:reference_red_hat_and_centos_software_and_installation_requirements.html["Conditions requises pour l'installation et le logiciel Linux"].

. Sur le système Red Hat Enterprise Linux 8.x, installez la même version que celle du logiciel Unified Manager sur le système Red Hat Enterprise Linux 7.x.
+
Voir link:concept_install_unified_manager_on_rhel_or_centos.html["Installation de Unified Manager sous Linux"].

+
Ne lancez pas l'interface utilisateur et ne configurez aucun cluster, utilisateur ou paramètre d'authentification lorsque l'installation est terminée. Le fichier de sauvegarde remplit ces informations lors du processus de restauration.

. Sur le système Red Hat Enterprise Linux 7.x, dans le menu Administration de l'interface utilisateur Web, créez une sauvegarde Unified Manager, puis copiez le fichier de sauvegarde (`.7z` file) et le contenu du répertoire du référentiel de base de données (`/database-dumps-repo` sous-répertoire) vers un emplacement externe.
. Sur le système Red Hat Enterprise Linux 7.x, arrêtez Unified Manager.
. Sur le système Red Hat Enterprise Linux 8.x, copiez le fichier de sauvegarde (`.7z` file) de l'emplacement externe à `/opt/netapp/data/ocum-backup/` et les fichiers du référentiel de base de données vers le `/database-dumps-repo` sous le sous-répertoire `/ocum-backup` répertoire.
. Entrez la commande suivante pour restaurer la base de données Unified Manager à partir du fichier de sauvegarde :
+
`um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`

. Entrez l'adresse IP ou l'URL dans votre navigateur pour démarrer l'interface utilisateur Web Unified Manager, puis connectez-vous au système.


Une fois que vous avez vérifié que le système fonctionne correctement, vous pouvez supprimer Unified Manager du système Red Hat Enterprise Linux 7.x.

*Mise à niveau du système d'exploitation hôte sur le même serveur*

Procédez comme suit si vous ne disposez pas d'un système de rechange sur lequel vous pouvez installer le logiciel Red Hat Enterprise Linux 8.x.

. Dans le menu Administration de l'interface utilisateur Web, créez une sauvegarde Unified Manager, puis copiez le fichier de sauvegarde (`.7z` file) et le contenu du répertoire du référentiel de base de données (`/database-dumps-repo` sous-répertoire) vers un emplacement externe.
. Supprimez l'image Red Hat Enterprise Linux 7.x du système et essuyez complètement le système.
. Installez et configurez le logiciel Red Hat Enterprise Linux 8.x sur le même système.
+
Voir link:reference_red_hat_and_centos_software_and_installation_requirements.html["Conditions requises pour l'installation et le logiciel Linux"].

. Sur le système Red Hat Enterprise Linux 8.x, installez la même version du logiciel Unified Manager que sur le système Red Hat Enterprise Linux 7.x.
+
Voir link:concept_install_unified_manager_on_rhel_or_centos.html["Installation de Unified Manager sous Linux"].

+
Ne lancez pas l'interface utilisateur et ne configurez aucun cluster, utilisateur ou paramètre d'authentification lorsque l'installation est terminée. Le fichier de sauvegarde remplit ces informations lors du processus de restauration.

. Copiez le fichier de sauvegarde (`.7z` file) de l'emplacement externe à `/opt/netapp/data/ocum-backup/` et les fichiers du référentiel de base de données vers le `/database-dumps-repo` sous le sous-répertoire `/ocum-backup` répertoire.
. Entrez la commande suivante pour restaurer la base de données Unified Manager à partir du fichier de sauvegarde :
+
`um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`

. Entrez l'adresse IP ou l'URL dans votre navigateur pour démarrer l'interface utilisateur Web Unified Manager, puis connectez-vous au système.

