---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: 'Vous pouvez réinitialiser le mot de passe JBoss spécifique à l"instance défini lors de l"installation. Vous pouvez éventuellement réinitialiser le mot de passe si votre site requiert cette fonctionnalité de sécurité afin de remplacer le paramètre d"installation de Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.' 
---
= Modification du mot de passe JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez réinitialiser le mot de passe JBoss spécifique à l'instance défini lors de l'installation. Vous pouvez éventuellement réinitialiser le mot de passe si votre site requiert cette fonctionnalité de sécurité afin de remplacer le paramètre d'installation de Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.

* Vous devez disposer d'un accès utilisateur root au système Red Hat Enterprise Linux sur lequel Unified Manager est installé.
* Pour accéder à ces informations, vous devez pouvoir `password.sh` script dans le répertoire `/opt/netapp/essentials/bin`.


.Étapes
. Connectez-vous en tant qu'utilisateur root sur le système.
. Arrêter les services Unified Manager en entrant les commandes suivantes dans l'ordre indiqué :
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
N'arrêtez pas le logiciel MySQL associé.

. Entrez la commande suivante pour lancer le processus de modification du mot de passe :
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Lorsque vous y êtes invité, saisissez le nouveau mot de passe JBoss, puis saisissez-le une deuxième fois pour confirmation.
+
Notez que le mot de passe doit comporter entre 8 et 16 caractères et doit contenir au moins un chiffre, un majuscule et des caractères minuscules, et au moins l'un des caractères spéciaux suivants :

+
`+!@%^*-_+=[]:<>.?/~+`

. Une fois le script terminé, démarrez les services Unified Manager en entrant les commandes suivantes dans l'ordre indiqué :
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Une fois tous les services démarrés, vous pouvez vous connecter à l'interface utilisateur de Unified Manager.

