---
permalink: install-linux/task_restart_unified_manager.html 
sidebar: sidebar 
keywords: restart, unified manager 
summary: 'Il peut s"avérer nécessaire de redémarrer Unified Manager après avoir apporté des modifications à la configuration.' 
---
= Redémarrer Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il peut s'avérer nécessaire de redémarrer Unified Manager après avoir apporté des modifications à la configuration.

.Avant de commencer
Vous devez disposer d'un accès utilisateur root au serveur Red Hat Enterprise Linux sur lequel Unified Manager est installé.

.Étapes
. Connectez-vous en tant qu'utilisateur root au serveur sur lequel vous souhaitez redémarrer le service Unified Manager.
. Arrêtez le service Unified Manager et le service MySQL associé dans l'ordre suivant :
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
`systemctl stop mysqld`

. Démarrez les services MySQL et Unified Manager dans l'ordre suivant :
+
`systemctl start mysqld`

+
`systemctl start ocie`

+
`systemctl start ocieau`



[NOTE]
====
`mysqld` Est un programme démon requis pour démarrer et arrêter le serveur MySQL.

====