---
permalink: events/reference_cluster_events.html 
sidebar: sidebar 
keywords: cluster events, impact, area, availability, capacity, configuration, performance, security 
summary: 'Les événements de cluster fournissent des informations sur l"état des clusters, ce qui vous permet de contrôler les clusters pour identifier des problèmes potentiels. Les événements sont regroupés par zone d"impact et incluent le nom de l"événement, le nom de l"interruption, le niveau d"impact, le type de source et la gravité.' 
---
= Événements de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les événements de cluster fournissent des informations sur l'état des clusters, ce qui vous permet de contrôler les clusters pour identifier des problèmes potentiels. Les événements sont regroupés par zone d'impact et incluent le nom de l'événement, le nom de l'interruption, le niveau d'impact, le type de source et la gravité.



== Domaine d'impact : disponibilité

Un astérisque (*) identifie les événements EMS qui ont été convertis en événements Unified Manager.

|===
| Nom de l'événement (nom de l'argument) | Niveau d'impact | Type de source | Gravité 


 a| 
Le cluster ne dispose pas de disques de rechange (ocumEvtDisksNoSpares)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Cluster inaccessible(ocumEvtClusterUnreaccessible)
 a| 
Risques
 a| 
Cluster
 a| 
Erreur



 a| 
Echec de la surveillance du cluster(oocumEvtClusterMonitoringFailé)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Limites de capacité de la licence Cluster FabricPool enfreintes précédemment (ocumEvtExternalcapacityTierSpaceplein)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Début de la période de grâce NVMe-of *(nvmfGracePeriodStart)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Période de grâce active NVMe-of *(nvmfGracePeriodActive)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Délai de grâce NVMe-of expiré *(nvmfGracePeriodExpired)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Fenêtre de maintenance de l'objet démarrée(objectMaintenanceStarted)
 a| 
Événement
 a| 
Cluster
 a| 
Primordial



 a| 
Fin de la fenêtre de maintenance de l'objet(objectMaintenanceFenêtre fenêtré)
 a| 
Événement
 a| 
Cluster
 a| 
Informations



 a| 
Disques de rechange MetroCluster laissés derrière (ocumEvtSpareDiskgauches Behind)
 a| 
Risques
 a| 
Cluster
 a| 
Erreur



 a| 
Basculement automatique non planifié désactivé dans MetroCluster (fonction ocumEvtccAutomaticUnplanndSwitchOverDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Mot de passe utilisateur du cluster modifié *(cluster.passwd.changed)
 a| 
Événement
 a| 
Cluster
 a| 
Informations

|===


== Zone d'impact : capacité

|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Seuil de déséquilibre de la capacité du cluster dépassé(ocumConformanceNodeImbalanceWarning)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Planification des niveaux de cluster Cloud (clusterCloudTierPlaningAvertissement)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Resynchronisation de la réplication des miroirs FabricPool terminée * (date de préexécution)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement



 a| 
Espace FabricPool presque complet * (fabrication NearpoolyFull)
 a| 
Risques
 a| 
Cluster
 a| 
Erreur

|===


== Zone d'impact : configuration

|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Nœud ajouté (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Informations



 a| 
Nœud supprimé (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Informations



 a| 
Suppression du cluster (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Informations



 a| 
Échec de l'ajout du cluster (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Erreur



 a| 
Nom de cluster modifié (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Informations



 a| 
EMS d'urgence reçu (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Primordial



 a| 
EMS critique reçu (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Primordial



 a| 
Alerte EMS reçue (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Erreur



 a| 
Erreur EMS reçue (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement



 a| 
Avertissement reçu EMS (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement



 a| 
EMS de débogage reçu (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement



 a| 
Avis EMS reçu (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement



 a| 
Informations fournies par le SGE (non applicable)
 a| 
Événement
 a| 
Cluster
 a| 
Avertissement

|===
Les événements EMS ONTAP sont classés en trois niveaux de sévérité des événements dans Unified Manager.

|===


| Niveau de sévérité des événements Unified Manager | Niveau de sévérité des événements EMS ONTAP 


 a| 
Primordial
 a| 
Urgence

Primordial



 a| 
Erreur
 a| 
Alerte



 a| 
Avertissement
 a| 
Erreur

Avertissement

Débogage

Avertissement

Informatif

|===


== Zone d'impact : performances

|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Seuil de déséquilibre de charge du cluster dépassé()
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Seuil critique d'IOPS du cluster dépassé (ocumClusterIopsincident)
 a| 
Gestion des
 a| 
Cluster
 a| 
Primordial



 a| 
Seuil d'avertissement d'IOPS du cluster dépassé (ocumClusterIopsWarning)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Saturation du seuil critique du cluster MB/s (ocumClusterMbpsincident)
 a| 
Gestion des
 a| 
Cluster
 a| 
Primordial



 a| 
Seuil d'avertissement MB/s du cluster dépassé(avertissement ocumClusterMbpsWarning)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Seuil dynamique de cluster dépassé (ocumClusterDynamicEventWarning)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement

|===


== Zone d'impact : sécurité

|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Transport HTTPS AutoSupport désactivé (ocumClusterASUPHttsConfigredDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Le transfert de journal n'est pas crypté(ocumClusterAuditLogUncrypté)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Utilisateur Admin local par défaut activé (ocumClusterDefaultAdminEnabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Mode FIPS désactivé (fonction ocumClusterFipsDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Bannière de connexion désactivée (oocumClusterLoginBannerDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Bannière de connexion modifiée(ocumClusterLoginBannerChanged)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Destinations de transfert de journal modifiées (ocumLogForwarddesmodes Changed)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Modification des noms de serveur NTP (ocumNtpServerNamesChanged)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Le nombre de serveurs NTP est faible (securityConfigNTPServerCountLowRisk)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Les communications des pairs de cluster ne sont pas cryptées(octaPeerEncryptionDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
SSH utilise des Ciphers non sécurisés (ocumClusterSSHInSecure)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Protocole Telnet activé (ocumClusterTelnetEnabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Les mots de passe de certains comptes utilisateur ONTAP utilisent la fonction de hachage MD5 moins sécurisée (ocumClusterMD5PasswordHashUsed)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Le cluster utilise un certificat auto-signé (ocumClusterSelfSignedCertificate)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Cluster Remote Shell est activé (ocumClusterRshDisabled)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Certificat de cluster sur le point d'expirer(ocumEvtClusterCertificate AboutToExpire)
 a| 
Risques
 a| 
Cluster
 a| 
Avertissement



 a| 
Certificat de cluster expiré(ocumEvtClusterCertificateExpired)
 a| 
Risques
 a| 
Cluster
 a| 
Erreur

|===