---
permalink: events/reference_nvram_battery_events.html 
sidebar: sidebar 
keywords: nvram, battery, events, impact area, availability 
summary: 'Les événements relatifs à la batterie NVRAM fournissent des informations sur l"état des batteries afin que vous puissiez surveiller les problèmes potentiels. Les événements sont regroupés par zone d"impact et incluent le nom de l"événement et de l"interruption, le niveau d"impact, le type de source et la gravité.' 
---
= Découvrez les événements liés à la batterie NVRAM dans Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les événements relatifs à la batterie NVRAM fournissent des informations sur l'état des batteries afin que vous puissiez surveiller les problèmes potentiels. Les événements sont regroupés par zone d'impact et incluent le nom de l'événement et de l'interruption, le niveau d'impact, le type de source et la gravité.



[[impact-area-availability]]
== Domaine d'impact : disponibilité

|===
| Nom de l'événement (nom de l'argument) | Niveau d'impact | Type de source | Gravité 


 a| 
Batterie NVRAM faible (batterie ocumEvtNvramyLow)
 a| 
Risques
 a| 
Nœud
 a| 
Avertissement



 a| 
Batterie NVRAM déchargée (batterie ocumEvtNvramyDischargée)
 a| 
Risques
 a| 
Nœud
 a| 
Erreur



 a| 
Batterie NVRAM trop chargée (batterie ocumEvtNvramyOverCharged)
 a| 
Gestion des
 a| 
Nœud
 a| 
Primordial

|===