---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: 'Vous pouvez créer une relation SnapVault à l"aide de la page des détails de volume/intégrité, de sorte que les sauvegardes de données soient activées à des fins de protection sur des volumes.' 
---
= Création d'une relation de protection SnapVault à partir de la page des détails du volume / intégrité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une relation SnapVault à l'aide de la page des détails de volume/intégrité, de sorte que les sauvegardes de données soient activées à des fins de protection sur des volumes.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir configuré Workflow Automation pour effectuer cette tâche.


Le menu *Protect* ne s'affiche pas dans les cas suivants :

* Si les paramètres RBAC n'autorisent pas cette action : par exemple, si vous disposez uniquement des privilèges d'opérateur
* Lorsque l'ID du volume est inconnu : par exemple, lorsque vous avez une relation intercluster et que le cluster destination n'a pas encore été découvert


.Étapes
. Dans l'onglet *protection* de la page de détails *Volume / Santé*, cliquez avec le bouton droit de la souris sur un volume dans la vue topologique que vous souhaitez protéger.
. Sélectionnez *protéger* > *SnapVault* dans le menu.
+
La boîte de dialogue configurer la protection s'ouvre.

. Cliquez sur *SnapVault* pour afficher l'onglet *SnapVault* et configurer les informations de ressource secondaire.
. Cliquez sur *Advanced* pour définir la déduplication, la compression, la croissance automatique et la garantie d'espace selon les besoins, puis cliquez sur *Apply*.
. Renseignez la zone *destination information* et la zone *Relationship Settings* de la boîte de dialogue *Configure protection*.
. Cliquez sur *appliquer*.
+
Vous êtes renvoyé à la page Volume / Health details.

. Cliquez sur le lien de la tâche de configuration de la protection en haut de la page *Volume / Santé*.
+
La page Détails du travail s'affiche.

. Cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
+
Une fois les tâches terminées, les nouvelles relations s'affichent dans la vue topologique de la page Volume / Health details.


