---
permalink: data-protection/task_edit_protection_relationships_from_protection_volume.html 
sidebar: sidebar 
keywords: edit, protection, relationships, volume, relationships, page 
summary: Vous pouvez modifier les relations de protection existantes pour modifier le taux de transfert maximal, la stratégie de protection ou le planning de protection. Vous pouvez modifier une relation pour diminuer la bande passante utilisée pour les transferts ou pour augmenter la fréquence des transferts programmés car les données changent souvent. 
---
= Modifier les relations de protection à partir de la page Relations de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les relations de protection existantes pour modifier le taux de transfert maximal, la stratégie de protection ou le planning de protection. Vous pouvez modifier une relation pour diminuer la bande passante utilisée pour les transferts ou pour augmenter la fréquence des transferts programmés car les données changent souvent.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

Les volumes sélectionnés doivent être des destinations de relation de protection. Vous ne pouvez pas modifier les relations lorsque les volumes source, les volumes de partage de charge ou les volumes qui ne sont pas de destination d'une relation SnapMirror ou SnapVault sont sélectionnés.

.Étapes
. Dans la page *Volume Relationship*, sélectionnez dans la liste des volumes un ou plusieurs volumes du même SVM pour lesquels vous souhaitez modifier les paramètres de relation, puis sélectionnez *Edit* dans la barre d'outils.
+
La boîte de dialogue Modifier la relation s'affiche.

. Dans la boîte de dialogue *Modifier la relation*, modifiez le taux de transfert maximal, la stratégie de protection ou le calendrier de protection, selon les besoins.
. Cliquez sur *appliquer*.
+
Les modifications sont appliquées aux relations sélectionnées.


