---
permalink: data-protection/task_resynchronize_protection_relationships.html 
sidebar: sidebar 
keywords: resynchronize, protection, relationships, volume, relationships page 
summary: 'Dans la page Volume relations, vous pouvez resynchroniser une relation pour effectuer une restauration à partir d"un événement qui a désactivé votre volume source ou si vous souhaitez modifier la source actuelle vers un autre volume.' 
---
= Resynchroniser les relations de protection à partir de la page Relations de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans la page Volume relations, vous pouvez resynchroniser une relation pour effectuer une restauration à partir d'un événement qui a désactivé votre volume source ou si vous souhaitez modifier la source actuelle vers un autre volume.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir configuré Workflow Automation.


.Étapes
. Dans la page *Volume relations*, sélectionnez un ou plusieurs volumes avec des relations suspendues et, dans la barre d'outils, cliquez sur *Resynchroniser*.
+
La boîte de dialogue Resynchroniser s'affiche.

. Dans l'onglet *Resynchronisation Options*, sélectionnez une priorité de transfert et le taux de transfert maximal.
. Cliquez sur *copies snapshot source*, puis, dans la colonne *copie snapshot*, cliquez sur *par défaut*.
+
La boîte de dialogue Sélectionner une copie Snapshot source s'affiche.

. Pour spécifier une copie Snapshot existante plutôt que de transférer la copie Snapshot par défaut, cliquez sur *copie Snapshot existante* et sélectionnez une copie Snapshot dans la liste.
. Cliquez sur *soumettre*.
+
Vous revenez à la boîte de dialogue Resynchroniser.

. Si vous avez sélectionné plusieurs sources à resynchroniser, cliquez sur *default* pour la source suivante pour laquelle vous souhaitez spécifier une copie Snapshot existante.
. Cliquez sur *Submit* pour lancer le travail de resynchronisation.
+
Le travail de resynchronisation est démarré, vous êtes renvoyé à la page relations de volume et un lien de travaux s'affiche en haut de la page.

. *Facultatif:* cliquez sur *Afficher les travaux* sur la page *relations de volume* pour suivre l'état de chaque travail de resynchronisation.
+
Une liste filtrée des travaux s'affiche.

. *Facultatif:* cliquez sur la flèche *Retour* de votre navigateur pour revenir à la page *Volume relations*.
+
L'opération de resynchronisation est terminée lorsque toutes les tâches du travail ont été terminées avec succès.


