---
permalink: data-protection/task_break_snapmirror_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: break, snapmirror, relationship, volume, health details 
summary: 'Vous pouvez interrompre une relation de protection à partir de la page des détails de volume/intégrité et arrêter les transferts de données entre un volume source et un volume cible dans une relation SnapMirror. Vous pouvez briser une relation lorsque vous souhaitez migrer des données, pour la reprise d"activité ou pour le test d"application. Le volume de destination est modifié en volume de lecture-écriture. Vous ne pouvez pas interrompre une relation SnapVault.' 
---
= Briser une relation SnapMirror depuis la page des détails du volume / intégrité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez interrompre une relation de protection à partir de la page des détails de volume/intégrité et arrêter les transferts de données entre un volume source et un volume cible dans une relation SnapMirror. Vous pouvez briser une relation lorsque vous souhaitez migrer des données, pour la reprise d'activité ou pour le test d'application. Le volume de destination est modifié en volume de lecture-écriture. Vous ne pouvez pas interrompre une relation SnapVault.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir configuré Workflow Automation.


.Étapes
. Dans l'onglet *protection* de la page *Volume / Santé*, sélectionnez dans la topologie la relation SnapMirror que vous souhaitez interrompre.
. Cliquez avec le bouton droit de la souris sur la destination et sélectionnez *Pause* dans le menu.
+
La boîte de dialogue rompre la relation s'affiche.

. Cliquez sur *Continuer* pour rompre la relation.
. Dans la topologie, vérifiez que la relation est rompue.

