---
permalink: data-protection/task_remove_protection_relationship.html 
sidebar: sidebar 
keywords: remove, protection, relationship, volume, relationships page 
summary: Depuis la page Relations de volumes, supprimez définitivement une relation de protection entre une source et une destination. Cette action est irréversible. 
---
= Supprimez une relation de protection depuis la page Volume Relationships dans Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans la page relations de volume, vous pouvez supprimer une relation de protection pour supprimer définitivement une relation existante entre la source et la destination sélectionnées : par exemple, lorsque vous souhaitez créer une relation à l'aide d'une destination différente. Cette opération supprime toutes les métadonnées et ne peut pas être annulée.

.Avant de commencer
* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir configuré Workflow Automation.


.Étapes
. Dans la page *Volume relations*, sélectionnez un ou plusieurs volumes avec des relations de protection que vous souhaitez supprimer et, dans la barre d'outils, cliquez sur *Remove*.
+
La boîte de dialogue Supprimer la relation s'affiche.

. Cliquez sur *Continuer* pour supprimer la relation.
+
La relation est supprimée de la page relations de volume.


