---
permalink: data-protection/task_restore_data_use_health_volume_details_page.html 
sidebar: sidebar 
keywords: restore, data, volume, health details page 
summary: 'Vous pouvez restaurer des fichiers, des répertoires ou un volume entier à partir d"une copie Snapshot remplacés ou supprimés. Pour ce faire, utilisez la fonctionnalité de restauration de la page Détails du volume/intégrité.' 
---
= Restauration des données à l'aide des pages de détails Volume et Volume/intégrité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer des fichiers, des répertoires ou un volume entier à partir d'une copie Snapshot remplacés ou supprimés. Pour ce faire, utilisez la fonctionnalité de restauration des pages d'informations sur le volume et le volume/l'état.

.Avant de commencer
Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.


NOTE: Notez les points suivants :

* Vous ne pouvez pas restaurer les flux de fichiers NTFS.
* L'option de restauration n'est pas disponible lorsque :
+
** L'ID du volume est inconnu : par exemple, lorsque vous disposez d'une relation intercluster et que le cluster destination n'a pas encore été découvert.
** Le volume est configuré pour la réplication SnapMirror synchrone.




.Étapes
. Dans le volet de navigation de gauche, accédez à *Storage > volumes*.
. Sélectionnez le volume et cliquez sur le bouton *Restaurer*. Vous pouvez également cliquer sur le volume pour accéder à *Volume / Détails de l'état de santé > actions > Restaurer*. La boîte de dialogue Restaurer s'affiche. Pour plus d'informations sur cette page, reportez-vous à la section link:../data-protection/reference_restore_dialog_box.html["Restaurer la boîte de dialogue"].
. Sélectionnez le volume et la copie Snapshot depuis lesquels vous souhaitez restaurer les données, si elles sont différentes de celles par défaut.
. Sélectionnez les éléments à restaurer, par exemple la LUN source.
+
Vous pouvez restaurer tout le volume ou spécifier les dossiers et les fichiers à restaurer.

. Sélectionnez l'emplacement auquel vous souhaitez restaurer les éléments sélectionnés : *emplacement d'origine* ou *autre emplacement existant*.
. Si vous sélectionnez un autre emplacement existant, effectuez l'une des opérations suivantes :
+
** Dans le champ de texte chemin de restauration, saisissez le chemin d'accès de l'emplacement auquel vous souhaitez restaurer les données, puis cliquez sur *Sélectionner le répertoire*.
** Cliquez sur *Parcourir* pour lancer la boîte de dialogue Parcourir les répertoires et effectuez les opérations suivantes :
+
... Sélectionnez le cluster de destination, la VM de stockage (SVM) et le volume vers lequel vous souhaitez restaurer.
... Dans la table Nom, sélectionnez un nom de répertoire à restaurer.
... Cliquez sur *Sélectionner répertoire*.




. Cliquez sur *Restaurer*.
+
Le processus de restauration commence. Un travail est créé en arrière-plan pour terminer le processus de restauration.

. Pour afficher la progression du travail, accédez à *protection > travaux* dans le volet de navigation de gauche pour afficher l'état du travail de restauration dans la liste des travaux.
+
[NOTE]
====
Si une opération de restauration échoue entre des clusters Cloud Volumes ONTAP HA avec une erreur NDMP, vous devrez peut-être ajouter une route AWS explicite dans le cluster de destination afin que la destination puisse communiquer avec la LIF de cluster management du système source. Vous effectuez cette étape de configuration en utilisant BlueXP.

====

