---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 'A partir de la vue Santé : tous les volumes, vous pouvez créer plusieurs relations de protection SnapMirror simultanément en sélectionnant plusieurs volumes sur la même VM de stockage.' 
---
= Création d'une relation de protection SnapMirror depuis la vue Santé : tous les volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de la vue Santé : tous les volumes, vous pouvez créer plusieurs relations de protection SnapMirror simultanément en sélectionnant plusieurs volumes sur la même VM de stockage.

*Ce dont vous aurez besoin*

* Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.
* Vous devez avoir configuré Workflow Automation.


Le menu *Protect* ne s'affiche pas dans les cas suivants :

* Si les paramètres RBAC n'autorisent pas cette action : par exemple, si vous disposez uniquement des privilèges d'opérateur
* Lorsque l'ID du volume est inconnu : par exemple, lorsque vous avez une relation intercluster et que le cluster destination n'a pas encore été découvert


.Étapes
. Dans la vue *Health: All volumes*, sélectionnez un volume que vous souhaitez protéger.
+
Alternativement, pour créer plusieurs relations de protection sur le même SVM, sélectionnez un ou plusieurs volumes dans la vue Health: All volumes, et cliquez sur *Protect* > *SnapMirror* dans la barre d'outils.

+
La boîte de dialogue configurer la protection s'affiche.

. Cliquez sur *SnapMirror* pour afficher l'onglet *SnapMirror* et configurer les informations de destination.
. Cliquez sur *Avancé* pour définir la garantie d'espace, selon les besoins, puis cliquez sur *appliquer*.
. Renseignez la zone *destination information* et la zone *Relationship Settings* de l'onglet *SnapMirror*.
. Cliquez sur *appliquer*.
+
Vous êtes renvoyé à la vue Santé: Tous les volumes.

. Cliquez sur le lien du travail de configuration de la protection en haut de la vue *Santé : tous les volumes*.
+
Si vous créez une seule relation de protection, la page Détails du travail s'affiche. Cependant, si vous créez plusieurs relations de protection, la liste de tous les travaux associés à l'opération de protection s'affiche.

. Effectuez l'une des opérations suivantes :
+
** Si vous n'avez qu'un seul travail, cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
** Si vous avez plusieurs travaux :
+
... Cliquez sur un travail dans la liste des travaux.
... Cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
... Utilisez le bouton *Retour* pour revenir à la liste filtrée et afficher un autre travail.






En fonction du SVM de destination que vous avez spécifié lors de la configuration ou des options que vous avez activées dans vos paramètres avancés, la relation SnapMirror résultante peut être l'une des variantes suivantes :

* Si vous avez spécifié un SVM de destination qui s'exécute sous la même version ou plus récente de ONTAP que celui du volume source, une relation SnapMirror basée sur la réplication de bloc est le résultat par défaut.
* Si vous avez spécifié un SVM de destination qui s'exécute sous la même version ou plus récente de ONTAP que celui du volume source, mais que vous avez activé la réplication flexible de version dans les paramètres avancés, il en résulte une relation SnapMirror avec la réplication flexible de la version.
* Si vous avez spécifié un SVM de destination qui s'exécute sous une version antérieure de ONTAP par rapport au volume source, et la version précédente prend en charge la réplication flexible de la version, une relation SnapMirror avec la réplication flexible de la version est le résultat automatique.

