---
permalink: data-protection/view-lun-relationships.html 
sidebar: sidebar 
keywords: LUN, SnapMirror active sync, Consistency Group, CG 
summary: Vue unifiée des LUN protégées par la synchronisation active SnapMirror. 
---
= Contrôle des LUN dans une relation de groupe de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si votre environnement ONTAP prend en charge la synchronisation active SnapMirror sur
Protégez les applications avec des LUN ; vous pouvez afficher et contrôler ces LUN sur Active IQ Unified Manager.

La synchronisation active SnapMirror garantit un objectif de délai de restauration nul en cas de basculement dans des environnements SAN. Dans un déploiement typique prenant en charge la synchronisation active SnapMirror, les LUN sur des volumes sont protégées par des relations de groupe de cohérence.

Ces LUN primaires et secondaires sont des LUN composites ou une paire de LUN de réplica avec le même UUID et le même numéro de série. Les opérations d'E/S (lecture et écriture) sont multiplexées entre les sites source et de destination sur ces LUN composites, pour une meilleure transparence.

Pour afficher les LUN composites, vous devez ajouter et découvrir les clusters principal et secondaire avec les LUN faisant partie de la relation de groupe de cohérence sur Unified Manager. Seules les LUN iSCSI et FCP sont prises en charge.

Pour plus d'informations sur la synchronisation active SnapMirror, reportez-vous à la section link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Documentation ONTAP 9 pour SnapMirror Active Sync (anciennement SM-BC)"].

Pour afficher les LUN composites dans votre environnement, effectuez la procédure suivante :

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage* > *LUNs*.
. Dans le menu Affichage, sélectionnez *relation* > *tous les LUN*.
+
La relation : toutes les LUN s'affichent.



Vous pouvez afficher les détails de la LUN, tels que le nom de la LUN, le volume, la machine virtuelle de stockage hébergeant la LUN, le cluster, le groupe de cohérence et la LUN partenaire. Vous pouvez cliquer sur chacun de ces composants pour accéder à une vue détaillée. Cliquez sur Groupe de cohérence pour accéder à la page relations.

Cliquez sur le LUN partenaire pour afficher les détails de configuration dans l'onglet SAN de la page Storage VM Details de la VM de stockage correspondant à la VM de stockage sur laquelle est hébergée la LUN partenaire. Les informations telles que les initiateurs et les groupes initiateurs, ainsi que d'autres aspects de la LUN partenaire s'affichent.

Vous pouvez exécuter les fonctions standard de tri, de filtrage, de génération et de téléchargement des rapports des LUN protégées de votre environnement au niveau de la grille.
